#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 119
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 60
#define ALIAS_COUNT 1
#define TOKEN_COUNT 33
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 8
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 8

enum {
  sym_identifier = 1,
  aux_sym_content_token1 = 2,
  anon_sym_LBRACE_LBRACE = 3,
  anon_sym_LBRACE_LBRACE_DASH = 4,
  anon_sym_LBRACE_LBRACE_TILDE = 5,
  anon_sym_RBRACE_RBRACE = 6,
  anon_sym_DASH_RBRACE_RBRACE = 7,
  anon_sym_TILDE_RBRACE_RBRACE = 8,
  anon_sym_LBRACE_POUND = 9,
  aux_sym_comment_token1 = 10,
  anon_sym_RBRACE = 11,
  anon_sym_LPAREN = 12,
  anon_sym_RPAREN = 13,
  anon_sym_null = 14,
  anon_sym_none = 15,
  sym_number = 16,
  anon_sym_true = 17,
  anon_sym_false = 18,
  sym_string = 19,
  anon_sym_DQUOTE = 20,
  anon_sym_BSLASH_DQUOTE = 21,
  anon_sym_BSLASH_POUND = 22,
  anon_sym_BSLASH_BSLASH = 23,
  aux_sym_interpolated_string_token1 = 24,
  anon_sym_POUND_LBRACE = 25,
  anon_sym_LBRACK = 26,
  anon_sym_COMMA = 27,
  anon_sym_RBRACK = 28,
  anon_sym_LBRACE = 29,
  anon_sym_COLON = 30,
  anon_sym_EQ_GT = 31,
  anon_sym_DOT = 32,
  sym_template = 33,
  sym__source_element = 34,
  sym_content = 35,
  sym_output_directive = 36,
  sym_comment = 37,
  sym_expression = 38,
  sym_primary_expression = 39,
  sym_parenthesized_expression = 40,
  sym_null = 41,
  sym_boolean = 42,
  sym_interpolated_string = 43,
  sym_array = 44,
  sym_object = 45,
  sym_pair = 46,
  sym__property_name = 47,
  sym_computed_property_name = 48,
  sym_arrow_function = 49,
  sym_formal_parameters = 50,
  sym_pattern = 51,
  sym_member_expression = 52,
  sym_subscript_expression = 53,
  aux_sym_template_repeat1 = 54,
  aux_sym_content_repeat1 = 55,
  aux_sym_interpolated_string_repeat1 = 56,
  aux_sym_array_repeat1 = 57,
  aux_sym_object_repeat1 = 58,
  aux_sym_formal_parameters_repeat1 = 59,
  alias_sym_property_identifier = 60,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [aux_sym_content_token1] = "content_token1",
  [anon_sym_LBRACE_LBRACE] = "{{",
  [anon_sym_LBRACE_LBRACE_DASH] = "{{-",
  [anon_sym_LBRACE_LBRACE_TILDE] = "{{~",
  [anon_sym_RBRACE_RBRACE] = "}}",
  [anon_sym_DASH_RBRACE_RBRACE] = "-}}",
  [anon_sym_TILDE_RBRACE_RBRACE] = "~}}",
  [anon_sym_LBRACE_POUND] = "{#",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_null] = "null",
  [anon_sym_none] = "none",
  [sym_number] = "number",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_string] = "string",
  [anon_sym_DQUOTE] = "\"",
  [anon_sym_BSLASH_DQUOTE] = "\\\"",
  [anon_sym_BSLASH_POUND] = "\\#",
  [anon_sym_BSLASH_BSLASH] = "\\\\",
  [aux_sym_interpolated_string_token1] = "interpolated_string_token1",
  [anon_sym_POUND_LBRACE] = "#{",
  [anon_sym_LBRACK] = "[",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LBRACE] = "{",
  [anon_sym_COLON] = ":",
  [anon_sym_EQ_GT] = "=>",
  [anon_sym_DOT] = ".",
  [sym_template] = "template",
  [sym__source_element] = "_source_element",
  [sym_content] = "content",
  [sym_output_directive] = "output_directive",
  [sym_comment] = "comment",
  [sym_expression] = "expression",
  [sym_primary_expression] = "primary_expression",
  [sym_parenthesized_expression] = "parenthesized_expression",
  [sym_null] = "null",
  [sym_boolean] = "boolean",
  [sym_interpolated_string] = "interpolated_string",
  [sym_array] = "array",
  [sym_object] = "object",
  [sym_pair] = "pair",
  [sym__property_name] = "_property_name",
  [sym_computed_property_name] = "computed_property_name",
  [sym_arrow_function] = "arrow_function",
  [sym_formal_parameters] = "formal_parameters",
  [sym_pattern] = "pattern",
  [sym_member_expression] = "member_expression",
  [sym_subscript_expression] = "subscript_expression",
  [aux_sym_template_repeat1] = "template_repeat1",
  [aux_sym_content_repeat1] = "content_repeat1",
  [aux_sym_interpolated_string_repeat1] = "interpolated_string_repeat1",
  [aux_sym_array_repeat1] = "array_repeat1",
  [aux_sym_object_repeat1] = "object_repeat1",
  [aux_sym_formal_parameters_repeat1] = "formal_parameters_repeat1",
  [alias_sym_property_identifier] = "property_identifier",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [aux_sym_content_token1] = aux_sym_content_token1,
  [anon_sym_LBRACE_LBRACE] = anon_sym_LBRACE_LBRACE,
  [anon_sym_LBRACE_LBRACE_DASH] = anon_sym_LBRACE_LBRACE_DASH,
  [anon_sym_LBRACE_LBRACE_TILDE] = anon_sym_LBRACE_LBRACE_TILDE,
  [anon_sym_RBRACE_RBRACE] = anon_sym_RBRACE_RBRACE,
  [anon_sym_DASH_RBRACE_RBRACE] = anon_sym_DASH_RBRACE_RBRACE,
  [anon_sym_TILDE_RBRACE_RBRACE] = anon_sym_TILDE_RBRACE_RBRACE,
  [anon_sym_LBRACE_POUND] = anon_sym_LBRACE_POUND,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_null] = anon_sym_null,
  [anon_sym_none] = anon_sym_none,
  [sym_number] = sym_number,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_string] = sym_string,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [anon_sym_BSLASH_DQUOTE] = anon_sym_BSLASH_DQUOTE,
  [anon_sym_BSLASH_POUND] = anon_sym_BSLASH_POUND,
  [anon_sym_BSLASH_BSLASH] = anon_sym_BSLASH_BSLASH,
  [aux_sym_interpolated_string_token1] = aux_sym_interpolated_string_token1,
  [anon_sym_POUND_LBRACE] = anon_sym_POUND_LBRACE,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_EQ_GT] = anon_sym_EQ_GT,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_template] = sym_template,
  [sym__source_element] = sym__source_element,
  [sym_content] = sym_content,
  [sym_output_directive] = sym_output_directive,
  [sym_comment] = sym_comment,
  [sym_expression] = sym_expression,
  [sym_primary_expression] = sym_primary_expression,
  [sym_parenthesized_expression] = sym_parenthesized_expression,
  [sym_null] = sym_null,
  [sym_boolean] = sym_boolean,
  [sym_interpolated_string] = sym_interpolated_string,
  [sym_array] = sym_array,
  [sym_object] = sym_object,
  [sym_pair] = sym_pair,
  [sym__property_name] = sym__property_name,
  [sym_computed_property_name] = sym_computed_property_name,
  [sym_arrow_function] = sym_arrow_function,
  [sym_formal_parameters] = sym_formal_parameters,
  [sym_pattern] = sym_pattern,
  [sym_member_expression] = sym_member_expression,
  [sym_subscript_expression] = sym_subscript_expression,
  [aux_sym_template_repeat1] = aux_sym_template_repeat1,
  [aux_sym_content_repeat1] = aux_sym_content_repeat1,
  [aux_sym_interpolated_string_repeat1] = aux_sym_interpolated_string_repeat1,
  [aux_sym_array_repeat1] = aux_sym_array_repeat1,
  [aux_sym_object_repeat1] = aux_sym_object_repeat1,
  [aux_sym_formal_parameters_repeat1] = aux_sym_formal_parameters_repeat1,
  [alias_sym_property_identifier] = alias_sym_property_identifier,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_content_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACE_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_LBRACE_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_LBRACE_TILDE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_RBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TILDE_RBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_POUND] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_null] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_none] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_interpolated_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_POUND_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_template] = {
    .visible = true,
    .named = true,
  },
  [sym__source_element] = {
    .visible = false,
    .named = true,
  },
  [sym_content] = {
    .visible = true,
    .named = true,
  },
  [sym_output_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_primary_expression] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_parenthesized_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_null] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_interpolated_string] = {
    .visible = true,
    .named = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [sym_object] = {
    .visible = true,
    .named = true,
  },
  [sym_pair] = {
    .visible = true,
    .named = true,
  },
  [sym__property_name] = {
    .visible = false,
    .named = true,
  },
  [sym_computed_property_name] = {
    .visible = true,
    .named = true,
  },
  [sym_arrow_function] = {
    .visible = true,
    .named = true,
  },
  [sym_formal_parameters] = {
    .visible = true,
    .named = true,
  },
  [sym_pattern] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_member_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_subscript_expression] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_template_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_content_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_interpolated_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_object_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_formal_parameters_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_property_identifier] = {
    .visible = true,
    .named = true,
  },
};

enum {
  field_body = 1,
  field_index = 2,
  field_key = 3,
  field_object = 4,
  field_parameter = 5,
  field_parameters = 6,
  field_property = 7,
  field_value = 8,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_body] = "body",
  [field_index] = "index",
  [field_key] = "key",
  [field_object] = "object",
  [field_parameter] = "parameter",
  [field_parameters] = "parameters",
  [field_property] = "property",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [2] = {.index = 0, .length = 2},
  [4] = {.index = 2, .length = 2},
  [5] = {.index = 4, .length = 2},
  [6] = {.index = 6, .length = 2},
  [7] = {.index = 8, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_body, 2},
    {field_parameter, 0},
  [2] =
    {field_object, 0},
    {field_property, 2},
  [4] =
    {field_body, 2},
    {field_parameters, 0},
  [6] =
    {field_key, 0},
    {field_value, 2},
  [8] =
    {field_index, 2},
    {field_object, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = sym_string,
  },
  [3] = {
    [1] = sym_string,
  },
  [4] = {
    [2] = alias_sym_property_identifier,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 2,
  [4] = 4,
  [5] = 5,
  [6] = 4,
  [7] = 7,
  [8] = 7,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 9,
  [15] = 10,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 24,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 42,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 43,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 20,
  [55] = 55,
  [56] = 53,
  [57] = 55,
  [58] = 58,
  [59] = 29,
  [60] = 36,
  [61] = 61,
  [62] = 62,
  [63] = 61,
  [64] = 34,
  [65] = 31,
  [66] = 28,
  [67] = 23,
  [68] = 27,
  [69] = 69,
  [70] = 21,
  [71] = 25,
  [72] = 30,
  [73] = 22,
  [74] = 38,
  [75] = 39,
  [76] = 37,
  [77] = 77,
  [78] = 35,
  [79] = 62,
  [80] = 33,
  [81] = 41,
  [82] = 40,
  [83] = 26,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 84,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 92,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 98,
  [100] = 100,
  [101] = 85,
  [102] = 91,
  [103] = 86,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 112,
  [114] = 108,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(21);
      if (lookahead == '"') ADVANCE(42);
      if (lookahead == '#') ADVANCE(9);
      if (lookahead == '\'') ADVANCE(7);
      if (lookahead == '(') ADVANCE(34);
      if (lookahead == ')') ADVANCE(35);
      if (lookahead == ',') ADVANCE(50);
      if (lookahead == '-') ADVANCE(13);
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == ':') ADVANCE(54);
      if (lookahead == '=') ADVANCE(8);
      if (lookahead == '[') ADVANCE(49);
      if (lookahead == '\\') ADVANCE(3);
      if (lookahead == ']') ADVANCE(51);
      if (lookahead == '{') ADVANCE(53);
      if (lookahead == '}') ADVANCE(33);
      if (lookahead == '~') ADVANCE(14);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (127 <= lookahead && lookahead <= 255)) ADVANCE(36);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(42);
      if (lookahead == '\'') ADVANCE(7);
      if (lookahead == '(') ADVANCE(34);
      if (lookahead == ')') ADVANCE(35);
      if (lookahead == ',') ADVANCE(50);
      if (lookahead == '-') ADVANCE(13);
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == '=') ADVANCE(8);
      if (lookahead == '[') ADVANCE(49);
      if (lookahead == ']') ADVANCE(51);
      if (lookahead == '{') ADVANCE(52);
      if (lookahead == '}') ADVANCE(12);
      if (lookahead == '~') ADVANCE(14);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (127 <= lookahead && lookahead <= 255)) ADVANCE(36);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(40);
      if (lookahead == '\\') ADVANCE(19);
      if (lookahead != 0 &&
          lookahead != '#') ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(43);
      if (lookahead == '#') ADVANCE(44);
      if (lookahead == '\\') ADVANCE(45);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(41);
      if (lookahead == '#') ADVANCE(9);
      if (lookahead == '\\') ADVANCE(3);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(46);
      if (lookahead != 0) ADVANCE(47);
      END_STATE();
    case 5:
      if (lookahead == '#') ADVANCE(32);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(5);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 6:
      if (lookahead == '#') ADVANCE(32);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == '\'') ADVANCE(40);
      if (lookahead == '\\') ADVANCE(18);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 8:
      if (lookahead == '>') ADVANCE(55);
      END_STATE();
    case 9:
      if (lookahead == '{') ADVANCE(48);
      END_STATE();
    case 10:
      if (lookahead == '}') ADVANCE(29);
      END_STATE();
    case 11:
      if (lookahead == '}') ADVANCE(30);
      END_STATE();
    case 12:
      if (lookahead == '}') ADVANCE(28);
      END_STATE();
    case 13:
      if (lookahead == '}') ADVANCE(10);
      END_STATE();
    case 14:
      if (lookahead == '}') ADVANCE(11);
      END_STATE();
    case 15:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(17);
      END_STATE();
    case 16:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(38);
      END_STATE();
    case 17:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      END_STATE();
    case 18:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(7);
      END_STATE();
    case 19:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 20:
      if (eof) ADVANCE(21);
      if (lookahead == '{') ADVANCE(22);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(23);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_content_token1);
      if (lookahead == '#') ADVANCE(31);
      if (lookahead == '{') ADVANCE(25);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_content_token1);
      if (lookahead == '{') ADVANCE(22);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(23);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_content_token1);
      if (lookahead != 0 &&
          lookahead != '{') ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE);
      if (lookahead == '-') ADVANCE(26);
      if (lookahead == '~') ADVANCE(27);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE_DASH);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE_TILDE);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_RBRACE_RBRACE);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_DASH_RBRACE_RBRACE);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_TILDE_RBRACE_RBRACE);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_LBRACE_POUND);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '#') ADVANCE(32);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(6);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (127 <= lookahead && lookahead <= 255)) ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(16);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      if (lookahead == '"') ADVANCE(40);
      if (lookahead == '\\') ADVANCE(19);
      if (lookahead != 0 &&
          lookahead != '#') ADVANCE(2);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_BSLASH_DQUOTE);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_BSLASH_POUND);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_BSLASH_BSLASH);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_interpolated_string_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(46);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '\\') ADVANCE(47);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_interpolated_string_token1);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '\\') ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_POUND_LBRACE);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead == '#') ADVANCE(31);
      if (lookahead == '{') ADVANCE(25);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_EQ_GT);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'f') ADVANCE(1);
      if (lookahead == 'n') ADVANCE(2);
      if (lookahead == 't') ADVANCE(3);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == 'a') ADVANCE(4);
      END_STATE();
    case 2:
      if (lookahead == 'o') ADVANCE(5);
      if (lookahead == 'u') ADVANCE(6);
      END_STATE();
    case 3:
      if (lookahead == 'r') ADVANCE(7);
      END_STATE();
    case 4:
      if (lookahead == 'l') ADVANCE(8);
      END_STATE();
    case 5:
      if (lookahead == 'n') ADVANCE(9);
      END_STATE();
    case 6:
      if (lookahead == 'l') ADVANCE(10);
      END_STATE();
    case 7:
      if (lookahead == 'u') ADVANCE(11);
      END_STATE();
    case 8:
      if (lookahead == 's') ADVANCE(12);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(13);
      END_STATE();
    case 10:
      if (lookahead == 'l') ADVANCE(14);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(15);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(16);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_none);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_null);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 20},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 20},
  [19] = {.lex_state = 20},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 4},
  [43] = {.lex_state = 4},
  [44] = {.lex_state = 4},
  [45] = {.lex_state = 4},
  [46] = {.lex_state = 20},
  [47] = {.lex_state = 20},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 4},
  [50] = {.lex_state = 20},
  [51] = {.lex_state = 20},
  [52] = {.lex_state = 4},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 1},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 5},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACE_DASH] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACE_TILDE] = ACTIONS(1),
    [anon_sym_DASH_RBRACE_RBRACE] = ACTIONS(1),
    [anon_sym_TILDE_RBRACE_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACE_POUND] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_null] = ACTIONS(1),
    [anon_sym_none] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_BSLASH_DQUOTE] = ACTIONS(1),
    [anon_sym_BSLASH_POUND] = ACTIONS(1),
    [anon_sym_BSLASH_BSLASH] = ACTIONS(1),
    [anon_sym_POUND_LBRACE] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_EQ_GT] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
  },
  [1] = {
    [sym_template] = STATE(118),
    [sym__source_element] = STATE(18),
    [sym_content] = STATE(18),
    [sym_output_directive] = STATE(18),
    [sym_comment] = STATE(18),
    [aux_sym_template_repeat1] = STATE(18),
    [aux_sym_content_repeat1] = STATE(47),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym_content_token1] = ACTIONS(5),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(7),
    [anon_sym_LBRACE_LBRACE_DASH] = ACTIONS(7),
    [anon_sym_LBRACE_LBRACE_TILDE] = ACTIONS(7),
    [anon_sym_LBRACE_POUND] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 15,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_RPAREN,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_LBRACE,
    STATE(26), 1,
      sym_primary_expression,
    STATE(98), 1,
      sym_expression,
    STATE(100), 1,
      sym_pattern,
    STATE(114), 1,
      sym_formal_parameters,
    ACTIONS(17), 2,
      anon_sym_null,
      anon_sym_none,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(62), 2,
      sym_member_expression,
      sym_subscript_expression,
    STATE(41), 7,
      sym_parenthesized_expression,
      sym_null,
      sym_boolean,
      sym_interpolated_string,
      sym_array,
      sym_object,
      sym_arrow_function,
  [56] = 15,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_RPAREN,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_LBRACE,
    STATE(26), 1,
      sym_primary_expression,
    STATE(99), 1,
      sym_expression,
    STATE(100), 1,
      sym_pattern,
    STATE(114), 1,
      sym_formal_parameters,
    ACTIONS(17), 2,
      anon_sym_null,
      anon_sym_none,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(62), 2,
      sym_member_expression,
      sym_subscript_expression,
    STATE(41), 7,
      sym_parenthesized_expression,
      sym_null,
      sym_boolean,
      sym_interpolated_string,
      sym_array,
      sym_object,
      sym_arrow_function,
  [112] = 13,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_LBRACE,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(31), 1,
      anon_sym_RBRACK,
    STATE(26), 1,
      sym_primary_expression,
    STATE(55), 1,
      sym_expression,
    STATE(114), 1,
      sym_formal_parameters,
    ACTIONS(17), 2,
      anon_sym_null,
      anon_sym_none,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(41), 9,
      sym_parenthesized_expression,
      sym_null,
      sym_boolean,
      sym_interpolated_string,
      sym_array,
      sym_object,
      sym_arrow_function,
      sym_member_expression,
      sym_subscript_expression,
  [163] = 14,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_LBRACE,
    ACTIONS(33), 1,
      sym_identifier,
    STATE(26), 1,
      sym_primary_expression,
    STATE(105), 1,
      sym_expression,
    STATE(106), 1,
      sym_pattern,
    STATE(114), 1,
      sym_formal_parameters,
    ACTIONS(17), 2,
      anon_sym_null,
      anon_sym_none,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(79), 2,
      sym_member_expression,
      sym_subscript_expression,
    STATE(41), 7,
      sym_parenthesized_expression,
      sym_null,
      sym_boolean,
      sym_interpolated_string,
      sym_array,
      sym_object,
      sym_arrow_function,
  [216] = 13,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_LBRACE,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(35), 1,
      anon_sym_RBRACK,
    STATE(26), 1,
      sym_primary_expression,
    STATE(57), 1,
      sym_expression,
    STATE(114), 1,
      sym_formal_parameters,
    ACTIONS(17), 2,
      anon_sym_null,
      anon_sym_none,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(41), 9,
      sym_parenthesized_expression,
      sym_null,
      sym_boolean,
      sym_interpolated_string,
      sym_array,
      sym_object,
      sym_arrow_function,
      sym_member_expression,
      sym_subscript_expression,
  [267] = 12,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_LBRACE,
    ACTIONS(29), 1,
      sym_identifier,
    STATE(23), 1,
      sym_expression,
    STATE(26), 1,
      sym_primary_expression,
    STATE(114), 1,
      sym_formal_parameters,
    ACTIONS(17), 2,
      anon_sym_null,
      anon_sym_none,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(41), 9,
      sym_parenthesized_expression,
      sym_null,
      sym_boolean,
      sym_interpolated_string,
      sym_array,
      sym_object,
      sym_arrow_function,
      sym_member_expression,
      sym_subscript_expression,
  [315] = 12,
    ACTIONS(37), 1,
      sym_identifier,
    ACTIONS(39), 1,
      anon_sym_LPAREN,
    ACTIONS(47), 1,
      anon_sym_DQUOTE,
    ACTIONS(49), 1,
      anon_sym_LBRACK,
    ACTIONS(51), 1,
      anon_sym_LBRACE,
    STATE(67), 1,
      sym_expression,
    STATE(83), 1,
      sym_primary_expression,
    STATE(108), 1,
      sym_formal_parameters,
    ACTIONS(41), 2,
      anon_sym_null,
      anon_sym_none,
    ACTIONS(43), 2,
      sym_number,
      sym_string,
    ACTIONS(45), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(81), 9,
      sym_parenthesized_expression,
      sym_null,
      sym_boolean,
      sym_interpolated_string,
      sym_array,
      sym_object,
      sym_arrow_function,
      sym_member_expression,
      sym_subscript_expression,
  [363] = 12,
    ACTIONS(37), 1,
      sym_identifier,
    ACTIONS(39), 1,
      anon_sym_LPAREN,
    ACTIONS(47), 1,
      anon_sym_DQUOTE,
    ACTIONS(49), 1,
      anon_sym_LBRACK,
    ACTIONS(51), 1,
      anon_sym_LBRACE,
    STATE(73), 1,
      sym_expression,
    STATE(83), 1,
      sym_primary_expression,
    STATE(108), 1,
      sym_formal_parameters,
    ACTIONS(41), 2,
      anon_sym_null,
      anon_sym_none,
    ACTIONS(43), 2,
      sym_number,
      sym_string,
    ACTIONS(45), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(81), 9,
      sym_parenthesized_expression,
      sym_null,
      sym_boolean,
      sym_interpolated_string,
      sym_array,
      sym_object,
      sym_arrow_function,
      sym_member_expression,
      sym_subscript_expression,
  [411] = 12,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_LBRACE,
    ACTIONS(29), 1,
      sym_identifier,
    STATE(26), 1,
      sym_primary_expression,
    STATE(101), 1,
      sym_expression,
    STATE(114), 1,
      sym_formal_parameters,
    ACTIONS(17), 2,
      anon_sym_null,
      anon_sym_none,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(41), 9,
      sym_parenthesized_expression,
      sym_null,
      sym_boolean,
      sym_interpolated_string,
      sym_array,
      sym_object,
      sym_arrow_function,
      sym_member_expression,
      sym_subscript_expression,
  [459] = 12,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_LBRACE,
    ACTIONS(29), 1,
      sym_identifier,
    STATE(26), 1,
      sym_primary_expression,
    STATE(58), 1,
      sym_expression,
    STATE(114), 1,
      sym_formal_parameters,
    ACTIONS(17), 2,
      anon_sym_null,
      anon_sym_none,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(41), 9,
      sym_parenthesized_expression,
      sym_null,
      sym_boolean,
      sym_interpolated_string,
      sym_array,
      sym_object,
      sym_arrow_function,
      sym_member_expression,
      sym_subscript_expression,
  [507] = 12,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_LBRACE,
    ACTIONS(29), 1,
      sym_identifier,
    STATE(26), 1,
      sym_primary_expression,
    STATE(95), 1,
      sym_expression,
    STATE(114), 1,
      sym_formal_parameters,
    ACTIONS(17), 2,
      anon_sym_null,
      anon_sym_none,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(41), 9,
      sym_parenthesized_expression,
      sym_null,
      sym_boolean,
      sym_interpolated_string,
      sym_array,
      sym_object,
      sym_arrow_function,
      sym_member_expression,
      sym_subscript_expression,
  [555] = 12,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_LBRACE,
    ACTIONS(29), 1,
      sym_identifier,
    STATE(26), 1,
      sym_primary_expression,
    STATE(69), 1,
      sym_expression,
    STATE(114), 1,
      sym_formal_parameters,
    ACTIONS(17), 2,
      anon_sym_null,
      anon_sym_none,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(41), 9,
      sym_parenthesized_expression,
      sym_null,
      sym_boolean,
      sym_interpolated_string,
      sym_array,
      sym_object,
      sym_arrow_function,
      sym_member_expression,
      sym_subscript_expression,
  [603] = 12,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_LBRACE,
    ACTIONS(29), 1,
      sym_identifier,
    STATE(22), 1,
      sym_expression,
    STATE(26), 1,
      sym_primary_expression,
    STATE(114), 1,
      sym_formal_parameters,
    ACTIONS(17), 2,
      anon_sym_null,
      anon_sym_none,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(41), 9,
      sym_parenthesized_expression,
      sym_null,
      sym_boolean,
      sym_interpolated_string,
      sym_array,
      sym_object,
      sym_arrow_function,
      sym_member_expression,
      sym_subscript_expression,
  [651] = 12,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_LBRACE,
    ACTIONS(29), 1,
      sym_identifier,
    STATE(26), 1,
      sym_primary_expression,
    STATE(85), 1,
      sym_expression,
    STATE(114), 1,
      sym_formal_parameters,
    ACTIONS(17), 2,
      anon_sym_null,
      anon_sym_none,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(41), 9,
      sym_parenthesized_expression,
      sym_null,
      sym_boolean,
      sym_interpolated_string,
      sym_array,
      sym_object,
      sym_arrow_function,
      sym_member_expression,
      sym_subscript_expression,
  [699] = 12,
    ACTIONS(37), 1,
      sym_identifier,
    ACTIONS(39), 1,
      anon_sym_LPAREN,
    ACTIONS(47), 1,
      anon_sym_DQUOTE,
    ACTIONS(49), 1,
      anon_sym_LBRACK,
    ACTIONS(51), 1,
      anon_sym_LBRACE,
    STATE(83), 1,
      sym_primary_expression,
    STATE(88), 1,
      sym_expression,
    STATE(108), 1,
      sym_formal_parameters,
    ACTIONS(41), 2,
      anon_sym_null,
      anon_sym_none,
    ACTIONS(43), 2,
      sym_number,
      sym_string,
    ACTIONS(45), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(81), 9,
      sym_parenthesized_expression,
      sym_null,
      sym_boolean,
      sym_interpolated_string,
      sym_array,
      sym_object,
      sym_arrow_function,
      sym_member_expression,
      sym_subscript_expression,
  [747] = 12,
    ACTIONS(37), 1,
      sym_identifier,
    ACTIONS(39), 1,
      anon_sym_LPAREN,
    ACTIONS(47), 1,
      anon_sym_DQUOTE,
    ACTIONS(49), 1,
      anon_sym_LBRACK,
    ACTIONS(51), 1,
      anon_sym_LBRACE,
    STATE(77), 1,
      sym_expression,
    STATE(83), 1,
      sym_primary_expression,
    STATE(108), 1,
      sym_formal_parameters,
    ACTIONS(41), 2,
      anon_sym_null,
      anon_sym_none,
    ACTIONS(43), 2,
      sym_number,
      sym_string,
    ACTIONS(45), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(81), 9,
      sym_parenthesized_expression,
      sym_null,
      sym_boolean,
      sym_interpolated_string,
      sym_array,
      sym_object,
      sym_arrow_function,
      sym_member_expression,
      sym_subscript_expression,
  [795] = 6,
    ACTIONS(5), 1,
      aux_sym_content_token1,
    ACTIONS(9), 1,
      anon_sym_LBRACE_POUND,
    ACTIONS(53), 1,
      ts_builtin_sym_end,
    STATE(47), 1,
      aux_sym_content_repeat1,
    ACTIONS(7), 3,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_DASH,
      anon_sym_LBRACE_LBRACE_TILDE,
    STATE(19), 5,
      sym__source_element,
      sym_content,
      sym_output_directive,
      sym_comment,
      aux_sym_template_repeat1,
  [820] = 6,
    ACTIONS(55), 1,
      ts_builtin_sym_end,
    ACTIONS(57), 1,
      aux_sym_content_token1,
    ACTIONS(63), 1,
      anon_sym_LBRACE_POUND,
    STATE(47), 1,
      aux_sym_content_repeat1,
    ACTIONS(60), 3,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_DASH,
      anon_sym_LBRACE_LBRACE_TILDE,
    STATE(19), 5,
      sym__source_element,
      sym_content,
      sym_output_directive,
      sym_comment,
      aux_sym_template_repeat1,
  [845] = 2,
    ACTIONS(68), 1,
      anon_sym_EQ_GT,
    ACTIONS(66), 8,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_TILDE_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DOT,
  [859] = 1,
    ACTIONS(70), 8,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_TILDE_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DOT,
  [870] = 3,
    ACTIONS(74), 1,
      anon_sym_LBRACK,
    ACTIONS(76), 1,
      anon_sym_DOT,
    ACTIONS(72), 6,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_TILDE_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [885] = 3,
    ACTIONS(74), 1,
      anon_sym_LBRACK,
    ACTIONS(76), 1,
      anon_sym_DOT,
    ACTIONS(78), 6,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_TILDE_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [900] = 6,
    ACTIONS(80), 1,
      sym_identifier,
    ACTIONS(82), 1,
      anon_sym_RBRACE,
    ACTIONS(84), 1,
      anon_sym_LPAREN,
    STATE(94), 1,
      sym_pair,
    ACTIONS(86), 2,
      sym_number,
      sym_string,
    STATE(115), 2,
      sym__property_name,
      sym_computed_property_name,
  [921] = 1,
    ACTIONS(88), 8,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_TILDE_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DOT,
  [932] = 3,
    ACTIONS(74), 1,
      anon_sym_LBRACK,
    ACTIONS(76), 1,
      anon_sym_DOT,
    ACTIONS(90), 6,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_TILDE_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [947] = 1,
    ACTIONS(92), 8,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_TILDE_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DOT,
  [958] = 1,
    ACTIONS(94), 8,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_TILDE_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DOT,
  [969] = 1,
    ACTIONS(96), 8,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_TILDE_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DOT,
  [980] = 1,
    ACTIONS(98), 8,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_TILDE_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DOT,
  [991] = 1,
    ACTIONS(100), 8,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_TILDE_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DOT,
  [1002] = 6,
    ACTIONS(84), 1,
      anon_sym_LPAREN,
    ACTIONS(102), 1,
      sym_identifier,
    ACTIONS(104), 1,
      anon_sym_RBRACE,
    STATE(92), 1,
      sym_pair,
    ACTIONS(86), 2,
      sym_number,
      sym_string,
    STATE(115), 2,
      sym__property_name,
      sym_computed_property_name,
  [1023] = 1,
    ACTIONS(106), 8,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_TILDE_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DOT,
  [1034] = 1,
    ACTIONS(108), 8,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_TILDE_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DOT,
  [1045] = 1,
    ACTIONS(110), 8,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_TILDE_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DOT,
  [1056] = 1,
    ACTIONS(112), 8,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_TILDE_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DOT,
  [1067] = 1,
    ACTIONS(114), 8,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_TILDE_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DOT,
  [1078] = 1,
    ACTIONS(116), 8,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_TILDE_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DOT,
  [1089] = 1,
    ACTIONS(118), 8,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_TILDE_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DOT,
  [1100] = 1,
    ACTIONS(120), 8,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_TILDE_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DOT,
  [1111] = 1,
    ACTIONS(66), 8,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_TILDE_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DOT,
  [1122] = 5,
    ACTIONS(122), 1,
      anon_sym_DQUOTE,
    ACTIONS(126), 1,
      aux_sym_interpolated_string_token1,
    ACTIONS(128), 1,
      anon_sym_POUND_LBRACE,
    STATE(45), 1,
      aux_sym_interpolated_string_repeat1,
    ACTIONS(124), 3,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_POUND,
      anon_sym_BSLASH_BSLASH,
  [1140] = 5,
    ACTIONS(128), 1,
      anon_sym_POUND_LBRACE,
    ACTIONS(130), 1,
      anon_sym_DQUOTE,
    ACTIONS(134), 1,
      aux_sym_interpolated_string_token1,
    STATE(44), 1,
      aux_sym_interpolated_string_repeat1,
    ACTIONS(132), 3,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_POUND,
      anon_sym_BSLASH_BSLASH,
  [1158] = 5,
    ACTIONS(126), 1,
      aux_sym_interpolated_string_token1,
    ACTIONS(128), 1,
      anon_sym_POUND_LBRACE,
    ACTIONS(136), 1,
      anon_sym_DQUOTE,
    STATE(45), 1,
      aux_sym_interpolated_string_repeat1,
    ACTIONS(124), 3,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_POUND,
      anon_sym_BSLASH_BSLASH,
  [1176] = 5,
    ACTIONS(138), 1,
      anon_sym_DQUOTE,
    ACTIONS(143), 1,
      aux_sym_interpolated_string_token1,
    ACTIONS(146), 1,
      anon_sym_POUND_LBRACE,
    STATE(45), 1,
      aux_sym_interpolated_string_repeat1,
    ACTIONS(140), 3,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_POUND,
      anon_sym_BSLASH_BSLASH,
  [1194] = 4,
    ACTIONS(149), 1,
      ts_builtin_sym_end,
    ACTIONS(151), 1,
      aux_sym_content_token1,
    STATE(46), 1,
      aux_sym_content_repeat1,
    ACTIONS(154), 4,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_DASH,
      anon_sym_LBRACE_LBRACE_TILDE,
      anon_sym_LBRACE_POUND,
  [1210] = 4,
    ACTIONS(156), 1,
      ts_builtin_sym_end,
    ACTIONS(158), 1,
      aux_sym_content_token1,
    STATE(46), 1,
      aux_sym_content_repeat1,
    ACTIONS(160), 4,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_DASH,
      anon_sym_LBRACE_LBRACE_TILDE,
      anon_sym_LBRACE_POUND,
  [1226] = 5,
    ACTIONS(84), 1,
      anon_sym_LPAREN,
    ACTIONS(162), 1,
      sym_identifier,
    STATE(104), 1,
      sym_pair,
    ACTIONS(86), 2,
      sym_number,
      sym_string,
    STATE(115), 2,
      sym__property_name,
      sym_computed_property_name,
  [1244] = 5,
    ACTIONS(128), 1,
      anon_sym_POUND_LBRACE,
    ACTIONS(164), 1,
      anon_sym_DQUOTE,
    ACTIONS(168), 1,
      aux_sym_interpolated_string_token1,
    STATE(42), 1,
      aux_sym_interpolated_string_repeat1,
    ACTIONS(166), 3,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_POUND,
      anon_sym_BSLASH_BSLASH,
  [1262] = 2,
    ACTIONS(170), 1,
      ts_builtin_sym_end,
    ACTIONS(172), 5,
      aux_sym_content_token1,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_DASH,
      anon_sym_LBRACE_LBRACE_TILDE,
      anon_sym_LBRACE_POUND,
  [1273] = 2,
    ACTIONS(174), 1,
      ts_builtin_sym_end,
    ACTIONS(176), 5,
      aux_sym_content_token1,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_DASH,
      anon_sym_LBRACE_LBRACE_TILDE,
      anon_sym_LBRACE_POUND,
  [1284] = 2,
    ACTIONS(180), 1,
      aux_sym_interpolated_string_token1,
    ACTIONS(178), 5,
      anon_sym_DQUOTE,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_POUND,
      anon_sym_BSLASH_BSLASH,
      anon_sym_POUND_LBRACE,
  [1295] = 3,
    ACTIONS(68), 1,
      anon_sym_EQ_GT,
    ACTIONS(66), 2,
      anon_sym_LBRACK,
      anon_sym_DOT,
    ACTIONS(182), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1307] = 2,
    ACTIONS(184), 1,
      anon_sym_EQ_GT,
    ACTIONS(66), 4,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_DOT,
  [1317] = 5,
    ACTIONS(74), 1,
      anon_sym_LBRACK,
    ACTIONS(76), 1,
      anon_sym_DOT,
    ACTIONS(186), 1,
      anon_sym_COMMA,
    ACTIONS(188), 1,
      anon_sym_RBRACK,
    STATE(102), 1,
      aux_sym_array_repeat1,
  [1333] = 4,
    ACTIONS(68), 1,
      anon_sym_EQ_GT,
    ACTIONS(182), 1,
      anon_sym_COMMA,
    ACTIONS(190), 1,
      anon_sym_RPAREN,
    ACTIONS(66), 2,
      anon_sym_LBRACK,
      anon_sym_DOT,
  [1347] = 5,
    ACTIONS(74), 1,
      anon_sym_LBRACK,
    ACTIONS(76), 1,
      anon_sym_DOT,
    ACTIONS(186), 1,
      anon_sym_COMMA,
    ACTIONS(193), 1,
      anon_sym_RBRACK,
    STATE(91), 1,
      aux_sym_array_repeat1,
  [1363] = 3,
    ACTIONS(74), 1,
      anon_sym_LBRACK,
    ACTIONS(76), 1,
      anon_sym_DOT,
    ACTIONS(195), 3,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_TILDE_RBRACE_RBRACE,
  [1375] = 1,
    ACTIONS(96), 4,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_DOT,
  [1382] = 1,
    ACTIONS(112), 4,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_DOT,
  [1389] = 4,
    ACTIONS(197), 1,
      anon_sym_RBRACE,
    ACTIONS(199), 1,
      anon_sym_COMMA,
    ACTIONS(201), 1,
      anon_sym_COLON,
    STATE(90), 1,
      aux_sym_object_repeat1,
  [1402] = 3,
    ACTIONS(182), 1,
      anon_sym_COMMA,
    ACTIONS(190), 1,
      anon_sym_RPAREN,
    ACTIONS(66), 2,
      anon_sym_LBRACK,
      anon_sym_DOT,
  [1413] = 4,
    ACTIONS(199), 1,
      anon_sym_COMMA,
    ACTIONS(201), 1,
      anon_sym_COLON,
    ACTIONS(203), 1,
      anon_sym_RBRACE,
    STATE(84), 1,
      aux_sym_object_repeat1,
  [1426] = 1,
    ACTIONS(108), 4,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_DOT,
  [1433] = 1,
    ACTIONS(100), 4,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_DOT,
  [1440] = 1,
    ACTIONS(94), 4,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_DOT,
  [1447] = 3,
    ACTIONS(205), 1,
      anon_sym_LBRACK,
    ACTIONS(207), 1,
      anon_sym_DOT,
    ACTIONS(78), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1458] = 1,
    ACTIONS(92), 4,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_DOT,
  [1465] = 3,
    ACTIONS(74), 1,
      anon_sym_LBRACK,
    ACTIONS(76), 1,
      anon_sym_DOT,
    ACTIONS(209), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1476] = 1,
    ACTIONS(70), 4,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_DOT,
  [1483] = 1,
    ACTIONS(88), 4,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_DOT,
  [1490] = 1,
    ACTIONS(98), 4,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_DOT,
  [1497] = 3,
    ACTIONS(205), 1,
      anon_sym_LBRACK,
    ACTIONS(207), 1,
      anon_sym_DOT,
    ACTIONS(72), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1508] = 1,
    ACTIONS(116), 4,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_DOT,
  [1515] = 1,
    ACTIONS(118), 4,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_DOT,
  [1522] = 1,
    ACTIONS(114), 4,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_DOT,
  [1529] = 3,
    ACTIONS(205), 1,
      anon_sym_LBRACK,
    ACTIONS(207), 1,
      anon_sym_DOT,
    ACTIONS(211), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1540] = 1,
    ACTIONS(110), 4,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_DOT,
  [1547] = 2,
    ACTIONS(66), 2,
      anon_sym_LBRACK,
      anon_sym_DOT,
    ACTIONS(182), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1556] = 1,
    ACTIONS(106), 4,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_DOT,
  [1563] = 1,
    ACTIONS(66), 4,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_DOT,
  [1570] = 1,
    ACTIONS(120), 4,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_DOT,
  [1577] = 3,
    ACTIONS(205), 1,
      anon_sym_LBRACK,
    ACTIONS(207), 1,
      anon_sym_DOT,
    ACTIONS(90), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1588] = 3,
    ACTIONS(199), 1,
      anon_sym_COMMA,
    ACTIONS(213), 1,
      anon_sym_RBRACE,
    STATE(89), 1,
      aux_sym_object_repeat1,
  [1598] = 3,
    ACTIONS(74), 1,
      anon_sym_LBRACK,
    ACTIONS(76), 1,
      anon_sym_DOT,
    ACTIONS(215), 1,
      anon_sym_RBRACK,
  [1608] = 3,
    ACTIONS(199), 1,
      anon_sym_COMMA,
    ACTIONS(217), 1,
      anon_sym_RBRACE,
    STATE(89), 1,
      aux_sym_object_repeat1,
  [1618] = 3,
    ACTIONS(219), 1,
      anon_sym_RPAREN,
    ACTIONS(221), 1,
      anon_sym_COMMA,
    STATE(97), 1,
      aux_sym_formal_parameters_repeat1,
  [1628] = 3,
    ACTIONS(205), 1,
      anon_sym_LBRACK,
    ACTIONS(207), 1,
      anon_sym_DOT,
    ACTIONS(223), 1,
      anon_sym_RBRACE,
  [1638] = 3,
    ACTIONS(225), 1,
      anon_sym_RBRACE,
    ACTIONS(227), 1,
      anon_sym_COMMA,
    STATE(89), 1,
      aux_sym_object_repeat1,
  [1648] = 3,
    ACTIONS(199), 1,
      anon_sym_COMMA,
    ACTIONS(230), 1,
      anon_sym_RBRACE,
    STATE(89), 1,
      aux_sym_object_repeat1,
  [1658] = 3,
    ACTIONS(186), 1,
      anon_sym_COMMA,
    ACTIONS(232), 1,
      anon_sym_RBRACK,
    STATE(96), 1,
      aux_sym_array_repeat1,
  [1668] = 3,
    ACTIONS(199), 1,
      anon_sym_COMMA,
    ACTIONS(234), 1,
      anon_sym_RBRACE,
    STATE(86), 1,
      aux_sym_object_repeat1,
  [1678] = 2,
    ACTIONS(201), 1,
      anon_sym_COLON,
    ACTIONS(236), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1686] = 3,
    ACTIONS(199), 1,
      anon_sym_COMMA,
    ACTIONS(238), 1,
      anon_sym_RBRACE,
    STATE(103), 1,
      aux_sym_object_repeat1,
  [1696] = 3,
    ACTIONS(74), 1,
      anon_sym_LBRACK,
    ACTIONS(76), 1,
      anon_sym_DOT,
    ACTIONS(240), 1,
      anon_sym_RPAREN,
  [1706] = 3,
    ACTIONS(209), 1,
      anon_sym_RBRACK,
    ACTIONS(242), 1,
      anon_sym_COMMA,
    STATE(96), 1,
      aux_sym_array_repeat1,
  [1716] = 3,
    ACTIONS(245), 1,
      anon_sym_RPAREN,
    ACTIONS(247), 1,
      anon_sym_COMMA,
    STATE(97), 1,
      aux_sym_formal_parameters_repeat1,
  [1726] = 3,
    ACTIONS(74), 1,
      anon_sym_LBRACK,
    ACTIONS(76), 1,
      anon_sym_DOT,
    ACTIONS(250), 1,
      anon_sym_RPAREN,
  [1736] = 3,
    ACTIONS(74), 1,
      anon_sym_LBRACK,
    ACTIONS(76), 1,
      anon_sym_DOT,
    ACTIONS(252), 1,
      anon_sym_RPAREN,
  [1746] = 3,
    ACTIONS(221), 1,
      anon_sym_COMMA,
    ACTIONS(254), 1,
      anon_sym_RPAREN,
    STATE(87), 1,
      aux_sym_formal_parameters_repeat1,
  [1756] = 3,
    ACTIONS(74), 1,
      anon_sym_LBRACK,
    ACTIONS(76), 1,
      anon_sym_DOT,
    ACTIONS(256), 1,
      anon_sym_RBRACK,
  [1766] = 3,
    ACTIONS(186), 1,
      anon_sym_COMMA,
    ACTIONS(258), 1,
      anon_sym_RBRACK,
    STATE(96), 1,
      aux_sym_array_repeat1,
  [1776] = 3,
    ACTIONS(199), 1,
      anon_sym_COMMA,
    ACTIONS(260), 1,
      anon_sym_RBRACE,
    STATE(89), 1,
      aux_sym_object_repeat1,
  [1786] = 1,
    ACTIONS(225), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1791] = 2,
    ACTIONS(74), 1,
      anon_sym_LBRACK,
    ACTIONS(76), 1,
      anon_sym_DOT,
  [1798] = 1,
    ACTIONS(245), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1803] = 1,
    ACTIONS(262), 1,
      anon_sym_EQ_GT,
  [1807] = 1,
    ACTIONS(264), 1,
      anon_sym_EQ_GT,
  [1811] = 1,
    ACTIONS(266), 1,
      anon_sym_EQ_GT,
  [1815] = 1,
    ACTIONS(268), 1,
      anon_sym_EQ_GT,
  [1819] = 1,
    ACTIONS(270), 1,
      anon_sym_COLON,
  [1823] = 1,
    ACTIONS(272), 1,
      sym_identifier,
  [1827] = 1,
    ACTIONS(274), 1,
      sym_identifier,
  [1831] = 1,
    ACTIONS(276), 1,
      anon_sym_EQ_GT,
  [1835] = 1,
    ACTIONS(278), 1,
      anon_sym_COLON,
  [1839] = 1,
    ACTIONS(280), 1,
      aux_sym_comment_token1,
  [1843] = 1,
    ACTIONS(282), 1,
      anon_sym_RBRACE,
  [1847] = 1,
    ACTIONS(284), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 56,
  [SMALL_STATE(4)] = 112,
  [SMALL_STATE(5)] = 163,
  [SMALL_STATE(6)] = 216,
  [SMALL_STATE(7)] = 267,
  [SMALL_STATE(8)] = 315,
  [SMALL_STATE(9)] = 363,
  [SMALL_STATE(10)] = 411,
  [SMALL_STATE(11)] = 459,
  [SMALL_STATE(12)] = 507,
  [SMALL_STATE(13)] = 555,
  [SMALL_STATE(14)] = 603,
  [SMALL_STATE(15)] = 651,
  [SMALL_STATE(16)] = 699,
  [SMALL_STATE(17)] = 747,
  [SMALL_STATE(18)] = 795,
  [SMALL_STATE(19)] = 820,
  [SMALL_STATE(20)] = 845,
  [SMALL_STATE(21)] = 859,
  [SMALL_STATE(22)] = 870,
  [SMALL_STATE(23)] = 885,
  [SMALL_STATE(24)] = 900,
  [SMALL_STATE(25)] = 921,
  [SMALL_STATE(26)] = 932,
  [SMALL_STATE(27)] = 947,
  [SMALL_STATE(28)] = 958,
  [SMALL_STATE(29)] = 969,
  [SMALL_STATE(30)] = 980,
  [SMALL_STATE(31)] = 991,
  [SMALL_STATE(32)] = 1002,
  [SMALL_STATE(33)] = 1023,
  [SMALL_STATE(34)] = 1034,
  [SMALL_STATE(35)] = 1045,
  [SMALL_STATE(36)] = 1056,
  [SMALL_STATE(37)] = 1067,
  [SMALL_STATE(38)] = 1078,
  [SMALL_STATE(39)] = 1089,
  [SMALL_STATE(40)] = 1100,
  [SMALL_STATE(41)] = 1111,
  [SMALL_STATE(42)] = 1122,
  [SMALL_STATE(43)] = 1140,
  [SMALL_STATE(44)] = 1158,
  [SMALL_STATE(45)] = 1176,
  [SMALL_STATE(46)] = 1194,
  [SMALL_STATE(47)] = 1210,
  [SMALL_STATE(48)] = 1226,
  [SMALL_STATE(49)] = 1244,
  [SMALL_STATE(50)] = 1262,
  [SMALL_STATE(51)] = 1273,
  [SMALL_STATE(52)] = 1284,
  [SMALL_STATE(53)] = 1295,
  [SMALL_STATE(54)] = 1307,
  [SMALL_STATE(55)] = 1317,
  [SMALL_STATE(56)] = 1333,
  [SMALL_STATE(57)] = 1347,
  [SMALL_STATE(58)] = 1363,
  [SMALL_STATE(59)] = 1375,
  [SMALL_STATE(60)] = 1382,
  [SMALL_STATE(61)] = 1389,
  [SMALL_STATE(62)] = 1402,
  [SMALL_STATE(63)] = 1413,
  [SMALL_STATE(64)] = 1426,
  [SMALL_STATE(65)] = 1433,
  [SMALL_STATE(66)] = 1440,
  [SMALL_STATE(67)] = 1447,
  [SMALL_STATE(68)] = 1458,
  [SMALL_STATE(69)] = 1465,
  [SMALL_STATE(70)] = 1476,
  [SMALL_STATE(71)] = 1483,
  [SMALL_STATE(72)] = 1490,
  [SMALL_STATE(73)] = 1497,
  [SMALL_STATE(74)] = 1508,
  [SMALL_STATE(75)] = 1515,
  [SMALL_STATE(76)] = 1522,
  [SMALL_STATE(77)] = 1529,
  [SMALL_STATE(78)] = 1540,
  [SMALL_STATE(79)] = 1547,
  [SMALL_STATE(80)] = 1556,
  [SMALL_STATE(81)] = 1563,
  [SMALL_STATE(82)] = 1570,
  [SMALL_STATE(83)] = 1577,
  [SMALL_STATE(84)] = 1588,
  [SMALL_STATE(85)] = 1598,
  [SMALL_STATE(86)] = 1608,
  [SMALL_STATE(87)] = 1618,
  [SMALL_STATE(88)] = 1628,
  [SMALL_STATE(89)] = 1638,
  [SMALL_STATE(90)] = 1648,
  [SMALL_STATE(91)] = 1658,
  [SMALL_STATE(92)] = 1668,
  [SMALL_STATE(93)] = 1678,
  [SMALL_STATE(94)] = 1686,
  [SMALL_STATE(95)] = 1696,
  [SMALL_STATE(96)] = 1706,
  [SMALL_STATE(97)] = 1716,
  [SMALL_STATE(98)] = 1726,
  [SMALL_STATE(99)] = 1736,
  [SMALL_STATE(100)] = 1746,
  [SMALL_STATE(101)] = 1756,
  [SMALL_STATE(102)] = 1766,
  [SMALL_STATE(103)] = 1776,
  [SMALL_STATE(104)] = 1786,
  [SMALL_STATE(105)] = 1791,
  [SMALL_STATE(106)] = 1798,
  [SMALL_STATE(107)] = 1803,
  [SMALL_STATE(108)] = 1807,
  [SMALL_STATE(109)] = 1811,
  [SMALL_STATE(110)] = 1815,
  [SMALL_STATE(111)] = 1819,
  [SMALL_STATE(112)] = 1823,
  [SMALL_STATE(113)] = 1827,
  [SMALL_STATE(114)] = 1831,
  [SMALL_STATE(115)] = 1835,
  [SMALL_STATE(116)] = 1839,
  [SMALL_STATE(117)] = 1843,
  [SMALL_STATE(118)] = 1847,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(116),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template, 1),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2),
  [57] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_template_repeat1, 2), SHIFT_REPEAT(47),
  [60] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_template_repeat1, 2), SHIFT_REPEAT(11),
  [63] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_template_repeat1, 2), SHIFT_REPEAT(116),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primary_expression, 1),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 3),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arrow_function, 3, .production_id = 2),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arrow_function, 3, .production_id = 5),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 3, .production_id = 3),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_member_expression, 3, .production_id = 4),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 4),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 3),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interpolated_string, 3),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 4, .production_id = 3),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_null, 1),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 4),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interpolated_string, 2),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subscript_expression, 4, .production_id = 7),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 2),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parenthesized_expression, 3),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 2),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1),
  [122] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [124] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [128] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [130] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [132] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [136] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_interpolated_string_repeat1, 2),
  [140] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_interpolated_string_repeat1, 2), SHIFT_REPEAT(45),
  [143] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_interpolated_string_repeat1, 2), SHIFT_REPEAT(45),
  [146] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_interpolated_string_repeat1, 2), SHIFT_REPEAT(16),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_content_repeat1, 2),
  [151] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_content_repeat1, 2), SHIFT_REPEAT(46),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_content_repeat1, 2),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_content, 1),
  [158] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [160] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_content, 1),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [164] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [166] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_output_directive, 3),
  [172] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_output_directive, 3),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3),
  [176] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 3),
  [178] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_interpolated_string_repeat1, 3),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_interpolated_string_repeat1, 3),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern, 1, .dynamic_precedence = -1),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [190] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_primary_expression, 1), REDUCE(sym_pattern, 1, .dynamic_precedence = -1),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__property_name, 1, .production_id = 1),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pair, 3, .production_id = 6),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_object_repeat1, 2),
  [227] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_object_repeat1, 2), SHIFT_REPEAT(48),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [236] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_object_repeat1, 2, .production_id = 3),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [242] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(13),
  [245] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_formal_parameters_repeat1, 2),
  [247] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_formal_parameters_repeat1, 2), SHIFT_REPEAT(5),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [262] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_formal_parameters, 3),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [266] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_formal_parameters, 2),
  [268] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_formal_parameters, 4),
  [270] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_computed_property_name, 3),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [284] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_twig(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
