#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 153
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 64
#define ALIAS_COUNT 1
#define TOKEN_COUNT 34
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 10
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 9

enum {
  sym_identifier = 1,
  aux_sym_content_token1 = 2,
  anon_sym_LBRACE_LBRACE = 3,
  anon_sym_LBRACE_LBRACE_DASH = 4,
  anon_sym_LBRACE_LBRACE_TILDE = 5,
  anon_sym_RBRACE_RBRACE = 6,
  anon_sym_DASH_RBRACE_RBRACE = 7,
  anon_sym_TILDE_RBRACE_RBRACE = 8,
  anon_sym_LBRACE_POUND = 9,
  aux_sym_comment_token1 = 10,
  anon_sym_RBRACE = 11,
  anon_sym_LPAREN = 12,
  anon_sym_RPAREN = 13,
  anon_sym_null = 14,
  anon_sym_none = 15,
  sym_number = 16,
  anon_sym_true = 17,
  anon_sym_false = 18,
  sym_string = 19,
  anon_sym_DQUOTE = 20,
  anon_sym_BSLASH_DQUOTE = 21,
  anon_sym_BSLASH_POUND = 22,
  anon_sym_BSLASH_BSLASH = 23,
  aux_sym_interpolated_string_token1 = 24,
  anon_sym_POUND_LBRACE = 25,
  anon_sym_LBRACK = 26,
  anon_sym_COMMA = 27,
  anon_sym_RBRACK = 28,
  anon_sym_LBRACE = 29,
  anon_sym_COLON = 30,
  anon_sym_EQ_GT = 31,
  anon_sym_DOT = 32,
  anon_sym_EQ = 33,
  sym_template = 34,
  sym__source_element = 35,
  sym_content = 36,
  sym_output_directive = 37,
  sym_comment = 38,
  sym_expression = 39,
  sym_primary_expression = 40,
  sym_parenthesized_expression = 41,
  sym_null = 42,
  sym_boolean = 43,
  sym_interpolated_string = 44,
  sym_array = 45,
  sym_object = 46,
  sym_pair = 47,
  sym__property_name = 48,
  sym_computed_property_name = 49,
  sym_arrow_function = 50,
  sym_formal_parameters = 51,
  sym_pattern = 52,
  sym_member_expression = 53,
  sym_subscript_expression = 54,
  sym_call_expression = 55,
  sym_arguments = 56,
  aux_sym_template_repeat1 = 57,
  aux_sym_content_repeat1 = 58,
  aux_sym_interpolated_string_repeat1 = 59,
  aux_sym_array_repeat1 = 60,
  aux_sym_object_repeat1 = 61,
  aux_sym_formal_parameters_repeat1 = 62,
  aux_sym_arguments_repeat1 = 63,
  alias_sym_property_identifier = 64,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [aux_sym_content_token1] = "content_token1",
  [anon_sym_LBRACE_LBRACE] = "{{",
  [anon_sym_LBRACE_LBRACE_DASH] = "{{-",
  [anon_sym_LBRACE_LBRACE_TILDE] = "{{~",
  [anon_sym_RBRACE_RBRACE] = "}}",
  [anon_sym_DASH_RBRACE_RBRACE] = "-}}",
  [anon_sym_TILDE_RBRACE_RBRACE] = "~}}",
  [anon_sym_LBRACE_POUND] = "{#",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_null] = "null",
  [anon_sym_none] = "none",
  [sym_number] = "number",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_string] = "string",
  [anon_sym_DQUOTE] = "\"",
  [anon_sym_BSLASH_DQUOTE] = "\\\"",
  [anon_sym_BSLASH_POUND] = "\\#",
  [anon_sym_BSLASH_BSLASH] = "\\\\",
  [aux_sym_interpolated_string_token1] = "interpolated_string_token1",
  [anon_sym_POUND_LBRACE] = "#{",
  [anon_sym_LBRACK] = "[",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LBRACE] = "{",
  [anon_sym_COLON] = ":",
  [anon_sym_EQ_GT] = "=>",
  [anon_sym_DOT] = ".",
  [anon_sym_EQ] = "=",
  [sym_template] = "template",
  [sym__source_element] = "_source_element",
  [sym_content] = "content",
  [sym_output_directive] = "output_directive",
  [sym_comment] = "comment",
  [sym_expression] = "expression",
  [sym_primary_expression] = "primary_expression",
  [sym_parenthesized_expression] = "parenthesized_expression",
  [sym_null] = "null",
  [sym_boolean] = "boolean",
  [sym_interpolated_string] = "interpolated_string",
  [sym_array] = "array",
  [sym_object] = "object",
  [sym_pair] = "pair",
  [sym__property_name] = "_property_name",
  [sym_computed_property_name] = "computed_property_name",
  [sym_arrow_function] = "arrow_function",
  [sym_formal_parameters] = "formal_parameters",
  [sym_pattern] = "pattern",
  [sym_member_expression] = "member_expression",
  [sym_subscript_expression] = "subscript_expression",
  [sym_call_expression] = "call_expression",
  [sym_arguments] = "arguments",
  [aux_sym_template_repeat1] = "template_repeat1",
  [aux_sym_content_repeat1] = "content_repeat1",
  [aux_sym_interpolated_string_repeat1] = "interpolated_string_repeat1",
  [aux_sym_array_repeat1] = "array_repeat1",
  [aux_sym_object_repeat1] = "object_repeat1",
  [aux_sym_formal_parameters_repeat1] = "formal_parameters_repeat1",
  [aux_sym_arguments_repeat1] = "arguments_repeat1",
  [alias_sym_property_identifier] = "property_identifier",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [aux_sym_content_token1] = aux_sym_content_token1,
  [anon_sym_LBRACE_LBRACE] = anon_sym_LBRACE_LBRACE,
  [anon_sym_LBRACE_LBRACE_DASH] = anon_sym_LBRACE_LBRACE_DASH,
  [anon_sym_LBRACE_LBRACE_TILDE] = anon_sym_LBRACE_LBRACE_TILDE,
  [anon_sym_RBRACE_RBRACE] = anon_sym_RBRACE_RBRACE,
  [anon_sym_DASH_RBRACE_RBRACE] = anon_sym_DASH_RBRACE_RBRACE,
  [anon_sym_TILDE_RBRACE_RBRACE] = anon_sym_TILDE_RBRACE_RBRACE,
  [anon_sym_LBRACE_POUND] = anon_sym_LBRACE_POUND,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_null] = anon_sym_null,
  [anon_sym_none] = anon_sym_none,
  [sym_number] = sym_number,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_string] = sym_string,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [anon_sym_BSLASH_DQUOTE] = anon_sym_BSLASH_DQUOTE,
  [anon_sym_BSLASH_POUND] = anon_sym_BSLASH_POUND,
  [anon_sym_BSLASH_BSLASH] = anon_sym_BSLASH_BSLASH,
  [aux_sym_interpolated_string_token1] = aux_sym_interpolated_string_token1,
  [anon_sym_POUND_LBRACE] = anon_sym_POUND_LBRACE,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_EQ_GT] = anon_sym_EQ_GT,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_template] = sym_template,
  [sym__source_element] = sym__source_element,
  [sym_content] = sym_content,
  [sym_output_directive] = sym_output_directive,
  [sym_comment] = sym_comment,
  [sym_expression] = sym_expression,
  [sym_primary_expression] = sym_primary_expression,
  [sym_parenthesized_expression] = sym_parenthesized_expression,
  [sym_null] = sym_null,
  [sym_boolean] = sym_boolean,
  [sym_interpolated_string] = sym_interpolated_string,
  [sym_array] = sym_array,
  [sym_object] = sym_object,
  [sym_pair] = sym_pair,
  [sym__property_name] = sym__property_name,
  [sym_computed_property_name] = sym_computed_property_name,
  [sym_arrow_function] = sym_arrow_function,
  [sym_formal_parameters] = sym_formal_parameters,
  [sym_pattern] = sym_pattern,
  [sym_member_expression] = sym_member_expression,
  [sym_subscript_expression] = sym_subscript_expression,
  [sym_call_expression] = sym_call_expression,
  [sym_arguments] = sym_arguments,
  [aux_sym_template_repeat1] = aux_sym_template_repeat1,
  [aux_sym_content_repeat1] = aux_sym_content_repeat1,
  [aux_sym_interpolated_string_repeat1] = aux_sym_interpolated_string_repeat1,
  [aux_sym_array_repeat1] = aux_sym_array_repeat1,
  [aux_sym_object_repeat1] = aux_sym_object_repeat1,
  [aux_sym_formal_parameters_repeat1] = aux_sym_formal_parameters_repeat1,
  [aux_sym_arguments_repeat1] = aux_sym_arguments_repeat1,
  [alias_sym_property_identifier] = alias_sym_property_identifier,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_content_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACE_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_LBRACE_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_LBRACE_TILDE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_RBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TILDE_RBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_POUND] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_null] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_none] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_interpolated_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_POUND_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_template] = {
    .visible = true,
    .named = true,
  },
  [sym__source_element] = {
    .visible = false,
    .named = true,
  },
  [sym_content] = {
    .visible = true,
    .named = true,
  },
  [sym_output_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_primary_expression] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_parenthesized_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_null] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_interpolated_string] = {
    .visible = true,
    .named = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [sym_object] = {
    .visible = true,
    .named = true,
  },
  [sym_pair] = {
    .visible = true,
    .named = true,
  },
  [sym__property_name] = {
    .visible = false,
    .named = true,
  },
  [sym_computed_property_name] = {
    .visible = true,
    .named = true,
  },
  [sym_arrow_function] = {
    .visible = true,
    .named = true,
  },
  [sym_formal_parameters] = {
    .visible = true,
    .named = true,
  },
  [sym_pattern] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_member_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_subscript_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_call_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_arguments] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_template_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_content_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_interpolated_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_object_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_formal_parameters_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_arguments_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_property_identifier] = {
    .visible = true,
    .named = true,
  },
};

enum {
  field_arguments = 1,
  field_body = 2,
  field_function = 3,
  field_index = 4,
  field_key = 5,
  field_object = 6,
  field_parameter = 7,
  field_parameters = 8,
  field_property = 9,
  field_value = 10,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_arguments] = "arguments",
  [field_body] = "body",
  [field_function] = "function",
  [field_index] = "index",
  [field_key] = "key",
  [field_object] = "object",
  [field_parameter] = "parameter",
  [field_parameters] = "parameters",
  [field_property] = "property",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [2] = {.index = 0, .length = 2},
  [3] = {.index = 2, .length = 2},
  [5] = {.index = 4, .length = 2},
  [6] = {.index = 6, .length = 2},
  [7] = {.index = 8, .length = 2},
  [8] = {.index = 10, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_arguments, 1},
    {field_function, 0},
  [2] =
    {field_body, 2},
    {field_parameter, 0},
  [4] =
    {field_object, 0},
    {field_property, 2},
  [6] =
    {field_body, 2},
    {field_parameters, 0},
  [8] =
    {field_key, 0},
    {field_value, 2},
  [10] =
    {field_index, 2},
    {field_object, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = sym_string,
  },
  [4] = {
    [1] = sym_string,
  },
  [5] = {
    [2] = alias_sym_property_identifier,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 2,
  [4] = 4,
  [5] = 4,
  [6] = 6,
  [7] = 6,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 13,
  [16] = 16,
  [17] = 17,
  [18] = 9,
  [19] = 17,
  [20] = 12,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 53,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 57,
  [62] = 55,
  [63] = 63,
  [64] = 64,
  [65] = 56,
  [66] = 66,
  [67] = 59,
  [68] = 60,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 64,
  [73] = 29,
  [74] = 74,
  [75] = 75,
  [76] = 26,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 28,
  [84] = 27,
  [85] = 82,
  [86] = 45,
  [87] = 30,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 88,
  [92] = 47,
  [93] = 44,
  [94] = 40,
  [95] = 33,
  [96] = 35,
  [97] = 38,
  [98] = 39,
  [99] = 43,
  [100] = 37,
  [101] = 46,
  [102] = 48,
  [103] = 89,
  [104] = 49,
  [105] = 90,
  [106] = 50,
  [107] = 32,
  [108] = 34,
  [109] = 36,
  [110] = 41,
  [111] = 42,
  [112] = 112,
  [113] = 31,
  [114] = 114,
  [115] = 51,
  [116] = 52,
  [117] = 117,
  [118] = 118,
  [119] = 118,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 123,
  [127] = 127,
  [128] = 128,
  [129] = 129,
  [130] = 120,
  [131] = 131,
  [132] = 132,
  [133] = 133,
  [134] = 134,
  [135] = 134,
  [136] = 132,
  [137] = 129,
  [138] = 133,
  [139] = 139,
  [140] = 140,
  [141] = 141,
  [142] = 142,
  [143] = 143,
  [144] = 144,
  [145] = 141,
  [146] = 146,
  [147] = 147,
  [148] = 148,
  [149] = 149,
  [150] = 150,
  [151] = 143,
  [152] = 152,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(21);
      if (lookahead == '"') ADVANCE(42);
      if (lookahead == '#') ADVANCE(9);
      if (lookahead == '\'') ADVANCE(7);
      if (lookahead == '(') ADVANCE(34);
      if (lookahead == ')') ADVANCE(35);
      if (lookahead == ',') ADVANCE(50);
      if (lookahead == '-') ADVANCE(13);
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == ':') ADVANCE(54);
      if (lookahead == '=') ADVANCE(57);
      if (lookahead == '[') ADVANCE(49);
      if (lookahead == '\\') ADVANCE(3);
      if (lookahead == ']') ADVANCE(51);
      if (lookahead == '{') ADVANCE(53);
      if (lookahead == '}') ADVANCE(33);
      if (lookahead == '~') ADVANCE(14);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (127 <= lookahead && lookahead <= 255)) ADVANCE(36);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(42);
      if (lookahead == '\'') ADVANCE(7);
      if (lookahead == '(') ADVANCE(34);
      if (lookahead == ')') ADVANCE(35);
      if (lookahead == ',') ADVANCE(50);
      if (lookahead == '-') ADVANCE(13);
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == '=') ADVANCE(8);
      if (lookahead == '[') ADVANCE(49);
      if (lookahead == ']') ADVANCE(51);
      if (lookahead == '{') ADVANCE(52);
      if (lookahead == '}') ADVANCE(12);
      if (lookahead == '~') ADVANCE(14);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (127 <= lookahead && lookahead <= 255)) ADVANCE(36);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(40);
      if (lookahead == '\\') ADVANCE(19);
      if (lookahead != 0 &&
          lookahead != '#') ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(43);
      if (lookahead == '#') ADVANCE(44);
      if (lookahead == '\\') ADVANCE(45);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(41);
      if (lookahead == '#') ADVANCE(9);
      if (lookahead == '\\') ADVANCE(3);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(46);
      if (lookahead != 0) ADVANCE(47);
      END_STATE();
    case 5:
      if (lookahead == '#') ADVANCE(32);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(5);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 6:
      if (lookahead == '#') ADVANCE(32);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == '\'') ADVANCE(40);
      if (lookahead == '\\') ADVANCE(18);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 8:
      if (lookahead == '>') ADVANCE(55);
      END_STATE();
    case 9:
      if (lookahead == '{') ADVANCE(48);
      END_STATE();
    case 10:
      if (lookahead == '}') ADVANCE(29);
      END_STATE();
    case 11:
      if (lookahead == '}') ADVANCE(30);
      END_STATE();
    case 12:
      if (lookahead == '}') ADVANCE(28);
      END_STATE();
    case 13:
      if (lookahead == '}') ADVANCE(10);
      END_STATE();
    case 14:
      if (lookahead == '}') ADVANCE(11);
      END_STATE();
    case 15:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(17);
      END_STATE();
    case 16:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(38);
      END_STATE();
    case 17:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      END_STATE();
    case 18:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(7);
      END_STATE();
    case 19:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 20:
      if (eof) ADVANCE(21);
      if (lookahead == '{') ADVANCE(22);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(23);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_content_token1);
      if (lookahead == '#') ADVANCE(31);
      if (lookahead == '{') ADVANCE(25);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_content_token1);
      if (lookahead == '{') ADVANCE(22);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(23);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_content_token1);
      if (lookahead != 0 &&
          lookahead != '{') ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE);
      if (lookahead == '-') ADVANCE(26);
      if (lookahead == '~') ADVANCE(27);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE_DASH);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE_TILDE);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_RBRACE_RBRACE);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_DASH_RBRACE_RBRACE);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_TILDE_RBRACE_RBRACE);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_LBRACE_POUND);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '#') ADVANCE(32);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(6);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (127 <= lookahead && lookahead <= 255)) ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(16);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      if (lookahead == '"') ADVANCE(40);
      if (lookahead == '\\') ADVANCE(19);
      if (lookahead != 0 &&
          lookahead != '#') ADVANCE(2);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_BSLASH_DQUOTE);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_BSLASH_POUND);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_BSLASH_BSLASH);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_interpolated_string_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(46);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '\\') ADVANCE(47);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_interpolated_string_token1);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '\\') ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_POUND_LBRACE);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead == '#') ADVANCE(31);
      if (lookahead == '{') ADVANCE(25);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_EQ_GT);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '>') ADVANCE(55);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'f') ADVANCE(1);
      if (lookahead == 'n') ADVANCE(2);
      if (lookahead == 't') ADVANCE(3);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == 'a') ADVANCE(4);
      END_STATE();
    case 2:
      if (lookahead == 'o') ADVANCE(5);
      if (lookahead == 'u') ADVANCE(6);
      END_STATE();
    case 3:
      if (lookahead == 'r') ADVANCE(7);
      END_STATE();
    case 4:
      if (lookahead == 'l') ADVANCE(8);
      END_STATE();
    case 5:
      if (lookahead == 'n') ADVANCE(9);
      END_STATE();
    case 6:
      if (lookahead == 'l') ADVANCE(10);
      END_STATE();
    case 7:
      if (lookahead == 'u') ADVANCE(11);
      END_STATE();
    case 8:
      if (lookahead == 's') ADVANCE(12);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(13);
      END_STATE();
    case 10:
      if (lookahead == 'l') ADVANCE(14);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(15);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(16);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_none);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_null);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 20},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 20},
  [25] = {.lex_state = 20},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 1},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 4},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 4},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 4},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 20},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 4},
  [69] = {.lex_state = 1},
  [70] = {.lex_state = 20},
  [71] = {.lex_state = 4},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 20},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 4},
  [79] = {.lex_state = 20},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 0},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 0},
  [131] = {.lex_state = 0},
  [132] = {.lex_state = 0},
  [133] = {.lex_state = 0},
  [134] = {.lex_state = 0},
  [135] = {.lex_state = 0},
  [136] = {.lex_state = 0},
  [137] = {.lex_state = 0},
  [138] = {.lex_state = 0},
  [139] = {.lex_state = 0},
  [140] = {.lex_state = 0},
  [141] = {.lex_state = 0},
  [142] = {.lex_state = 5},
  [143] = {.lex_state = 0},
  [144] = {.lex_state = 0},
  [145] = {.lex_state = 0},
  [146] = {.lex_state = 0},
  [147] = {.lex_state = 0},
  [148] = {.lex_state = 0},
  [149] = {.lex_state = 0},
  [150] = {.lex_state = 0},
  [151] = {.lex_state = 0},
  [152] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACE_DASH] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACE_TILDE] = ACTIONS(1),
    [anon_sym_DASH_RBRACE_RBRACE] = ACTIONS(1),
    [anon_sym_TILDE_RBRACE_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACE_POUND] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_null] = ACTIONS(1),
    [anon_sym_none] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_BSLASH_DQUOTE] = ACTIONS(1),
    [anon_sym_BSLASH_POUND] = ACTIONS(1),
    [anon_sym_BSLASH_BSLASH] = ACTIONS(1),
    [anon_sym_POUND_LBRACE] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_EQ_GT] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
  },
  [1] = {
    [sym_template] = STATE(152),
    [sym__source_element] = STATE(25),
    [sym_content] = STATE(25),
    [sym_output_directive] = STATE(25),
    [sym_comment] = STATE(25),
    [aux_sym_template_repeat1] = STATE(25),
    [aux_sym_content_repeat1] = STATE(66),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym_content_token1] = ACTIONS(5),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(7),
    [anon_sym_LBRACE_LBRACE_DASH] = ACTIONS(7),
    [anon_sym_LBRACE_LBRACE_TILDE] = ACTIONS(7),
    [anon_sym_LBRACE_POUND] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 15,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_RPAREN,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_LBRACE,
    STATE(27), 1,
      sym_primary_expression,
    STATE(88), 1,
      sym_expression,
    STATE(131), 1,
      sym_pattern,
    STATE(151), 1,
      sym_formal_parameters,
    ACTIONS(17), 2,
      anon_sym_null,
      anon_sym_none,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(90), 2,
      sym_member_expression,
      sym_subscript_expression,
    STATE(46), 8,
      sym_parenthesized_expression,
      sym_null,
      sym_boolean,
      sym_interpolated_string,
      sym_array,
      sym_object,
      sym_arrow_function,
      sym_call_expression,
  [57] = 15,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_RPAREN,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_LBRACE,
    STATE(27), 1,
      sym_primary_expression,
    STATE(91), 1,
      sym_expression,
    STATE(131), 1,
      sym_pattern,
    STATE(151), 1,
      sym_formal_parameters,
    ACTIONS(17), 2,
      anon_sym_null,
      anon_sym_none,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(90), 2,
      sym_member_expression,
      sym_subscript_expression,
    STATE(46), 8,
      sym_parenthesized_expression,
      sym_null,
      sym_boolean,
      sym_interpolated_string,
      sym_array,
      sym_object,
      sym_arrow_function,
      sym_call_expression,
  [114] = 13,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_LBRACE,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(31), 1,
      anon_sym_RBRACK,
    STATE(27), 1,
      sym_primary_expression,
    STATE(61), 1,
      sym_expression,
    STATE(151), 1,
      sym_formal_parameters,
    ACTIONS(17), 2,
      anon_sym_null,
      anon_sym_none,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(46), 10,
      sym_parenthesized_expression,
      sym_null,
      sym_boolean,
      sym_interpolated_string,
      sym_array,
      sym_object,
      sym_arrow_function,
      sym_member_expression,
      sym_subscript_expression,
      sym_call_expression,
  [166] = 13,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_LBRACE,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(33), 1,
      anon_sym_RBRACK,
    STATE(27), 1,
      sym_primary_expression,
    STATE(57), 1,
      sym_expression,
    STATE(151), 1,
      sym_formal_parameters,
    ACTIONS(17), 2,
      anon_sym_null,
      anon_sym_none,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(46), 10,
      sym_parenthesized_expression,
      sym_null,
      sym_boolean,
      sym_interpolated_string,
      sym_array,
      sym_object,
      sym_arrow_function,
      sym_member_expression,
      sym_subscript_expression,
      sym_call_expression,
  [218] = 13,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_LBRACE,
    ACTIONS(35), 1,
      sym_identifier,
    ACTIONS(37), 1,
      anon_sym_RPAREN,
    STATE(27), 1,
      sym_primary_expression,
    STATE(65), 1,
      sym_expression,
    STATE(151), 1,
      sym_formal_parameters,
    ACTIONS(17), 2,
      anon_sym_null,
      anon_sym_none,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(46), 10,
      sym_parenthesized_expression,
      sym_null,
      sym_boolean,
      sym_interpolated_string,
      sym_array,
      sym_object,
      sym_arrow_function,
      sym_member_expression,
      sym_subscript_expression,
      sym_call_expression,
  [270] = 13,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_LBRACE,
    ACTIONS(39), 1,
      sym_identifier,
    ACTIONS(41), 1,
      anon_sym_RPAREN,
    STATE(27), 1,
      sym_primary_expression,
    STATE(56), 1,
      sym_expression,
    STATE(151), 1,
      sym_formal_parameters,
    ACTIONS(17), 2,
      anon_sym_null,
      anon_sym_none,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(46), 10,
      sym_parenthesized_expression,
      sym_null,
      sym_boolean,
      sym_interpolated_string,
      sym_array,
      sym_object,
      sym_arrow_function,
      sym_member_expression,
      sym_subscript_expression,
      sym_call_expression,
  [322] = 14,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_LBRACE,
    ACTIONS(43), 1,
      sym_identifier,
    STATE(27), 1,
      sym_primary_expression,
    STATE(117), 1,
      sym_expression,
    STATE(140), 1,
      sym_pattern,
    STATE(151), 1,
      sym_formal_parameters,
    ACTIONS(17), 2,
      anon_sym_null,
      anon_sym_none,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(105), 2,
      sym_member_expression,
      sym_subscript_expression,
    STATE(46), 8,
      sym_parenthesized_expression,
      sym_null,
      sym_boolean,
      sym_interpolated_string,
      sym_array,
      sym_object,
      sym_arrow_function,
      sym_call_expression,
  [376] = 12,
    ACTIONS(45), 1,
      sym_identifier,
    ACTIONS(47), 1,
      anon_sym_LPAREN,
    ACTIONS(55), 1,
      anon_sym_DQUOTE,
    ACTIONS(57), 1,
      anon_sym_LBRACK,
    ACTIONS(59), 1,
      anon_sym_LBRACE,
    STATE(76), 1,
      sym_expression,
    STATE(84), 1,
      sym_primary_expression,
    STATE(143), 1,
      sym_formal_parameters,
    ACTIONS(49), 2,
      anon_sym_null,
      anon_sym_none,
    ACTIONS(51), 2,
      sym_number,
      sym_string,
    ACTIONS(53), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(101), 10,
      sym_parenthesized_expression,
      sym_null,
      sym_boolean,
      sym_interpolated_string,
      sym_array,
      sym_object,
      sym_arrow_function,
      sym_member_expression,
      sym_subscript_expression,
      sym_call_expression,
  [425] = 12,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_LBRACE,
    ACTIONS(29), 1,
      sym_identifier,
    STATE(27), 1,
      sym_primary_expression,
    STATE(81), 1,
      sym_expression,
    STATE(151), 1,
      sym_formal_parameters,
    ACTIONS(17), 2,
      anon_sym_null,
      anon_sym_none,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(46), 10,
      sym_parenthesized_expression,
      sym_null,
      sym_boolean,
      sym_interpolated_string,
      sym_array,
      sym_object,
      sym_arrow_function,
      sym_member_expression,
      sym_subscript_expression,
      sym_call_expression,
  [474] = 12,
    ACTIONS(45), 1,
      sym_identifier,
    ACTIONS(47), 1,
      anon_sym_LPAREN,
    ACTIONS(55), 1,
      anon_sym_DQUOTE,
    ACTIONS(57), 1,
      anon_sym_LBRACK,
    ACTIONS(59), 1,
      anon_sym_LBRACE,
    STATE(80), 1,
      sym_expression,
    STATE(84), 1,
      sym_primary_expression,
    STATE(143), 1,
      sym_formal_parameters,
    ACTIONS(49), 2,
      anon_sym_null,
      anon_sym_none,
    ACTIONS(51), 2,
      sym_number,
      sym_string,
    ACTIONS(53), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(101), 10,
      sym_parenthesized_expression,
      sym_null,
      sym_boolean,
      sym_interpolated_string,
      sym_array,
      sym_object,
      sym_arrow_function,
      sym_member_expression,
      sym_subscript_expression,
      sym_call_expression,
  [523] = 12,
    ACTIONS(45), 1,
      sym_identifier,
    ACTIONS(47), 1,
      anon_sym_LPAREN,
    ACTIONS(55), 1,
      anon_sym_DQUOTE,
    ACTIONS(57), 1,
      anon_sym_LBRACK,
    ACTIONS(59), 1,
      anon_sym_LBRACE,
    STATE(73), 1,
      sym_expression,
    STATE(84), 1,
      sym_primary_expression,
    STATE(143), 1,
      sym_formal_parameters,
    ACTIONS(49), 2,
      anon_sym_null,
      anon_sym_none,
    ACTIONS(51), 2,
      sym_number,
      sym_string,
    ACTIONS(53), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(101), 10,
      sym_parenthesized_expression,
      sym_null,
      sym_boolean,
      sym_interpolated_string,
      sym_array,
      sym_object,
      sym_arrow_function,
      sym_member_expression,
      sym_subscript_expression,
      sym_call_expression,
  [572] = 12,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_LBRACE,
    ACTIONS(29), 1,
      sym_identifier,
    STATE(27), 1,
      sym_primary_expression,
    STATE(103), 1,
      sym_expression,
    STATE(151), 1,
      sym_formal_parameters,
    ACTIONS(17), 2,
      anon_sym_null,
      anon_sym_none,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(46), 10,
      sym_parenthesized_expression,
      sym_null,
      sym_boolean,
      sym_interpolated_string,
      sym_array,
      sym_object,
      sym_arrow_function,
      sym_member_expression,
      sym_subscript_expression,
      sym_call_expression,
  [621] = 12,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_LBRACE,
    ACTIONS(29), 1,
      sym_identifier,
    STATE(27), 1,
      sym_primary_expression,
    STATE(74), 1,
      sym_expression,
    STATE(151), 1,
      sym_formal_parameters,
    ACTIONS(17), 2,
      anon_sym_null,
      anon_sym_none,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(46), 10,
      sym_parenthesized_expression,
      sym_null,
      sym_boolean,
      sym_interpolated_string,
      sym_array,
      sym_object,
      sym_arrow_function,
      sym_member_expression,
      sym_subscript_expression,
      sym_call_expression,
  [670] = 12,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_LBRACE,
    ACTIONS(29), 1,
      sym_identifier,
    STATE(27), 1,
      sym_primary_expression,
    STATE(89), 1,
      sym_expression,
    STATE(151), 1,
      sym_formal_parameters,
    ACTIONS(17), 2,
      anon_sym_null,
      anon_sym_none,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(46), 10,
      sym_parenthesized_expression,
      sym_null,
      sym_boolean,
      sym_interpolated_string,
      sym_array,
      sym_object,
      sym_arrow_function,
      sym_member_expression,
      sym_subscript_expression,
      sym_call_expression,
  [719] = 12,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_LBRACE,
    ACTIONS(29), 1,
      sym_identifier,
    STATE(27), 1,
      sym_primary_expression,
    STATE(69), 1,
      sym_expression,
    STATE(151), 1,
      sym_formal_parameters,
    ACTIONS(17), 2,
      anon_sym_null,
      anon_sym_none,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(46), 10,
      sym_parenthesized_expression,
      sym_null,
      sym_boolean,
      sym_interpolated_string,
      sym_array,
      sym_object,
      sym_arrow_function,
      sym_member_expression,
      sym_subscript_expression,
      sym_call_expression,
  [768] = 12,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_LBRACE,
    ACTIONS(29), 1,
      sym_identifier,
    STATE(27), 1,
      sym_primary_expression,
    STATE(59), 1,
      sym_expression,
    STATE(151), 1,
      sym_formal_parameters,
    ACTIONS(17), 2,
      anon_sym_null,
      anon_sym_none,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(46), 10,
      sym_parenthesized_expression,
      sym_null,
      sym_boolean,
      sym_interpolated_string,
      sym_array,
      sym_object,
      sym_arrow_function,
      sym_member_expression,
      sym_subscript_expression,
      sym_call_expression,
  [817] = 12,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_LBRACE,
    ACTIONS(29), 1,
      sym_identifier,
    STATE(26), 1,
      sym_expression,
    STATE(27), 1,
      sym_primary_expression,
    STATE(151), 1,
      sym_formal_parameters,
    ACTIONS(17), 2,
      anon_sym_null,
      anon_sym_none,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(46), 10,
      sym_parenthesized_expression,
      sym_null,
      sym_boolean,
      sym_interpolated_string,
      sym_array,
      sym_object,
      sym_arrow_function,
      sym_member_expression,
      sym_subscript_expression,
      sym_call_expression,
  [866] = 12,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_LBRACE,
    ACTIONS(29), 1,
      sym_identifier,
    STATE(27), 1,
      sym_primary_expression,
    STATE(67), 1,
      sym_expression,
    STATE(151), 1,
      sym_formal_parameters,
    ACTIONS(17), 2,
      anon_sym_null,
      anon_sym_none,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(46), 10,
      sym_parenthesized_expression,
      sym_null,
      sym_boolean,
      sym_interpolated_string,
      sym_array,
      sym_object,
      sym_arrow_function,
      sym_member_expression,
      sym_subscript_expression,
      sym_call_expression,
  [915] = 12,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_LBRACE,
    ACTIONS(29), 1,
      sym_identifier,
    STATE(27), 1,
      sym_primary_expression,
    STATE(29), 1,
      sym_expression,
    STATE(151), 1,
      sym_formal_parameters,
    ACTIONS(17), 2,
      anon_sym_null,
      anon_sym_none,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(46), 10,
      sym_parenthesized_expression,
      sym_null,
      sym_boolean,
      sym_interpolated_string,
      sym_array,
      sym_object,
      sym_arrow_function,
      sym_member_expression,
      sym_subscript_expression,
      sym_call_expression,
  [964] = 12,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_LBRACE,
    ACTIONS(61), 1,
      sym_identifier,
    STATE(27), 1,
      sym_primary_expression,
    STATE(77), 1,
      sym_expression,
    STATE(151), 1,
      sym_formal_parameters,
    ACTIONS(17), 2,
      anon_sym_null,
      anon_sym_none,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(46), 10,
      sym_parenthesized_expression,
      sym_null,
      sym_boolean,
      sym_interpolated_string,
      sym_array,
      sym_object,
      sym_arrow_function,
      sym_member_expression,
      sym_subscript_expression,
      sym_call_expression,
  [1013] = 12,
    ACTIONS(45), 1,
      sym_identifier,
    ACTIONS(47), 1,
      anon_sym_LPAREN,
    ACTIONS(55), 1,
      anon_sym_DQUOTE,
    ACTIONS(57), 1,
      anon_sym_LBRACK,
    ACTIONS(59), 1,
      anon_sym_LBRACE,
    STATE(84), 1,
      sym_primary_expression,
    STATE(114), 1,
      sym_expression,
    STATE(143), 1,
      sym_formal_parameters,
    ACTIONS(49), 2,
      anon_sym_null,
      anon_sym_none,
    ACTIONS(51), 2,
      sym_number,
      sym_string,
    ACTIONS(53), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(101), 10,
      sym_parenthesized_expression,
      sym_null,
      sym_boolean,
      sym_interpolated_string,
      sym_array,
      sym_object,
      sym_arrow_function,
      sym_member_expression,
      sym_subscript_expression,
      sym_call_expression,
  [1062] = 12,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_LBRACE,
    ACTIONS(29), 1,
      sym_identifier,
    STATE(27), 1,
      sym_primary_expression,
    STATE(112), 1,
      sym_expression,
    STATE(151), 1,
      sym_formal_parameters,
    ACTIONS(17), 2,
      anon_sym_null,
      anon_sym_none,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(46), 10,
      sym_parenthesized_expression,
      sym_null,
      sym_boolean,
      sym_interpolated_string,
      sym_array,
      sym_object,
      sym_arrow_function,
      sym_member_expression,
      sym_subscript_expression,
      sym_call_expression,
  [1111] = 6,
    ACTIONS(63), 1,
      ts_builtin_sym_end,
    ACTIONS(65), 1,
      aux_sym_content_token1,
    ACTIONS(71), 1,
      anon_sym_LBRACE_POUND,
    STATE(66), 1,
      aux_sym_content_repeat1,
    ACTIONS(68), 3,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_DASH,
      anon_sym_LBRACE_LBRACE_TILDE,
    STATE(24), 5,
      sym__source_element,
      sym_content,
      sym_output_directive,
      sym_comment,
      aux_sym_template_repeat1,
  [1136] = 6,
    ACTIONS(5), 1,
      aux_sym_content_token1,
    ACTIONS(9), 1,
      anon_sym_LBRACE_POUND,
    ACTIONS(74), 1,
      ts_builtin_sym_end,
    STATE(66), 1,
      aux_sym_content_repeat1,
    ACTIONS(7), 3,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_DASH,
      anon_sym_LBRACE_LBRACE_TILDE,
    STATE(24), 5,
      sym__source_element,
      sym_content,
      sym_output_directive,
      sym_comment,
      aux_sym_template_repeat1,
  [1161] = 5,
    ACTIONS(78), 1,
      anon_sym_LPAREN,
    ACTIONS(80), 1,
      anon_sym_LBRACK,
    ACTIONS(82), 1,
      anon_sym_DOT,
    STATE(41), 1,
      sym_arguments,
    ACTIONS(76), 6,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_TILDE_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1182] = 5,
    ACTIONS(78), 1,
      anon_sym_LPAREN,
    ACTIONS(80), 1,
      anon_sym_LBRACK,
    ACTIONS(82), 1,
      anon_sym_DOT,
    STATE(42), 1,
      sym_arguments,
    ACTIONS(84), 6,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_TILDE_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1203] = 2,
    ACTIONS(88), 1,
      anon_sym_EQ_GT,
    ACTIONS(86), 9,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_TILDE_RBRACE_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DOT,
  [1218] = 5,
    ACTIONS(78), 1,
      anon_sym_LPAREN,
    ACTIONS(80), 1,
      anon_sym_LBRACK,
    ACTIONS(82), 1,
      anon_sym_DOT,
    STATE(41), 1,
      sym_arguments,
    ACTIONS(90), 6,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_TILDE_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1239] = 1,
    ACTIONS(92), 9,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_TILDE_RBRACE_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DOT,
  [1251] = 1,
    ACTIONS(94), 9,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_TILDE_RBRACE_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DOT,
  [1263] = 1,
    ACTIONS(96), 9,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_TILDE_RBRACE_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DOT,
  [1275] = 1,
    ACTIONS(98), 9,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_TILDE_RBRACE_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DOT,
  [1287] = 1,
    ACTIONS(100), 9,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_TILDE_RBRACE_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DOT,
  [1299] = 1,
    ACTIONS(102), 9,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_TILDE_RBRACE_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DOT,
  [1311] = 1,
    ACTIONS(104), 9,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_TILDE_RBRACE_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DOT,
  [1323] = 1,
    ACTIONS(106), 9,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_TILDE_RBRACE_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DOT,
  [1335] = 1,
    ACTIONS(108), 9,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_TILDE_RBRACE_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DOT,
  [1347] = 1,
    ACTIONS(110), 9,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_TILDE_RBRACE_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DOT,
  [1359] = 1,
    ACTIONS(112), 9,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_TILDE_RBRACE_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DOT,
  [1371] = 1,
    ACTIONS(114), 9,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_TILDE_RBRACE_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DOT,
  [1383] = 1,
    ACTIONS(114), 9,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_TILDE_RBRACE_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DOT,
  [1395] = 1,
    ACTIONS(116), 9,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_TILDE_RBRACE_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DOT,
  [1407] = 1,
    ACTIONS(118), 9,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_TILDE_RBRACE_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DOT,
  [1419] = 1,
    ACTIONS(120), 9,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_TILDE_RBRACE_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DOT,
  [1431] = 1,
    ACTIONS(86), 9,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_TILDE_RBRACE_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DOT,
  [1443] = 1,
    ACTIONS(122), 9,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_TILDE_RBRACE_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DOT,
  [1455] = 1,
    ACTIONS(124), 9,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_TILDE_RBRACE_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DOT,
  [1467] = 1,
    ACTIONS(126), 9,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_TILDE_RBRACE_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DOT,
  [1479] = 1,
    ACTIONS(128), 9,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_TILDE_RBRACE_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DOT,
  [1491] = 1,
    ACTIONS(130), 9,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_TILDE_RBRACE_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DOT,
  [1503] = 1,
    ACTIONS(132), 9,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_TILDE_RBRACE_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DOT,
  [1515] = 6,
    ACTIONS(134), 1,
      sym_identifier,
    ACTIONS(136), 1,
      anon_sym_RBRACE,
    ACTIONS(138), 1,
      anon_sym_LPAREN,
    STATE(120), 1,
      sym_pair,
    ACTIONS(140), 2,
      sym_number,
      sym_string,
    STATE(144), 2,
      sym__property_name,
      sym_computed_property_name,
  [1536] = 6,
    ACTIONS(138), 1,
      anon_sym_LPAREN,
    ACTIONS(142), 1,
      sym_identifier,
    ACTIONS(144), 1,
      anon_sym_RBRACE,
    STATE(130), 1,
      sym_pair,
    ACTIONS(140), 2,
      sym_number,
      sym_string,
    STATE(144), 2,
      sym__property_name,
      sym_computed_property_name,
  [1557] = 5,
    ACTIONS(146), 1,
      anon_sym_DQUOTE,
    ACTIONS(150), 1,
      aux_sym_interpolated_string_token1,
    ACTIONS(152), 1,
      anon_sym_POUND_LBRACE,
    STATE(68), 1,
      aux_sym_interpolated_string_repeat1,
    ACTIONS(148), 3,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_POUND,
      anon_sym_BSLASH_BSLASH,
  [1575] = 7,
    ACTIONS(78), 1,
      anon_sym_LPAREN,
    ACTIONS(80), 1,
      anon_sym_LBRACK,
    ACTIONS(82), 1,
      anon_sym_DOT,
    ACTIONS(154), 1,
      anon_sym_RPAREN,
    ACTIONS(156), 1,
      anon_sym_COMMA,
    STATE(41), 1,
      sym_arguments,
    STATE(129), 1,
      aux_sym_arguments_repeat1,
  [1597] = 7,
    ACTIONS(78), 1,
      anon_sym_LPAREN,
    ACTIONS(80), 1,
      anon_sym_LBRACK,
    ACTIONS(82), 1,
      anon_sym_DOT,
    ACTIONS(158), 1,
      anon_sym_COMMA,
    ACTIONS(160), 1,
      anon_sym_RBRACK,
    STATE(41), 1,
      sym_arguments,
    STATE(134), 1,
      aux_sym_array_repeat1,
  [1619] = 5,
    ACTIONS(138), 1,
      anon_sym_LPAREN,
    ACTIONS(162), 1,
      sym_identifier,
    STATE(139), 1,
      sym_pair,
    ACTIONS(140), 2,
      sym_number,
      sym_string,
    STATE(144), 2,
      sym__property_name,
      sym_computed_property_name,
  [1637] = 7,
    ACTIONS(78), 1,
      anon_sym_LPAREN,
    ACTIONS(80), 1,
      anon_sym_LBRACK,
    ACTIONS(82), 1,
      anon_sym_DOT,
    ACTIONS(156), 1,
      anon_sym_COMMA,
    ACTIONS(164), 1,
      anon_sym_RPAREN,
    STATE(41), 1,
      sym_arguments,
    STATE(126), 1,
      aux_sym_arguments_repeat1,
  [1659] = 5,
    ACTIONS(152), 1,
      anon_sym_POUND_LBRACE,
    ACTIONS(166), 1,
      anon_sym_DQUOTE,
    ACTIONS(170), 1,
      aux_sym_interpolated_string_token1,
    STATE(71), 1,
      aux_sym_interpolated_string_repeat1,
    ACTIONS(168), 3,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_POUND,
      anon_sym_BSLASH_BSLASH,
  [1677] = 7,
    ACTIONS(78), 1,
      anon_sym_LPAREN,
    ACTIONS(80), 1,
      anon_sym_LBRACK,
    ACTIONS(82), 1,
      anon_sym_DOT,
    ACTIONS(158), 1,
      anon_sym_COMMA,
    ACTIONS(172), 1,
      anon_sym_RBRACK,
    STATE(41), 1,
      sym_arguments,
    STATE(135), 1,
      aux_sym_array_repeat1,
  [1699] = 5,
    ACTIONS(152), 1,
      anon_sym_POUND_LBRACE,
    ACTIONS(174), 1,
      anon_sym_DQUOTE,
    ACTIONS(178), 1,
      aux_sym_interpolated_string_token1,
    STATE(60), 1,
      aux_sym_interpolated_string_repeat1,
    ACTIONS(176), 3,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_POUND,
      anon_sym_BSLASH_BSLASH,
  [1717] = 3,
    ACTIONS(88), 1,
      anon_sym_EQ_GT,
    ACTIONS(180), 1,
      anon_sym_EQ,
    ACTIONS(86), 5,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_DOT,
  [1731] = 3,
    ACTIONS(88), 1,
      anon_sym_EQ_GT,
    ACTIONS(182), 1,
      anon_sym_EQ,
    ACTIONS(86), 5,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_DOT,
  [1745] = 7,
    ACTIONS(78), 1,
      anon_sym_LPAREN,
    ACTIONS(80), 1,
      anon_sym_LBRACK,
    ACTIONS(82), 1,
      anon_sym_DOT,
    ACTIONS(156), 1,
      anon_sym_COMMA,
    ACTIONS(184), 1,
      anon_sym_RPAREN,
    STATE(41), 1,
      sym_arguments,
    STATE(137), 1,
      aux_sym_arguments_repeat1,
  [1767] = 4,
    ACTIONS(186), 1,
      ts_builtin_sym_end,
    ACTIONS(188), 1,
      aux_sym_content_token1,
    STATE(70), 1,
      aux_sym_content_repeat1,
    ACTIONS(190), 4,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_DASH,
      anon_sym_LBRACE_LBRACE_TILDE,
      anon_sym_LBRACE_POUND,
  [1783] = 7,
    ACTIONS(78), 1,
      anon_sym_LPAREN,
    ACTIONS(80), 1,
      anon_sym_LBRACK,
    ACTIONS(82), 1,
      anon_sym_DOT,
    ACTIONS(156), 1,
      anon_sym_COMMA,
    ACTIONS(192), 1,
      anon_sym_RPAREN,
    STATE(41), 1,
      sym_arguments,
    STATE(123), 1,
      aux_sym_arguments_repeat1,
  [1805] = 5,
    ACTIONS(152), 1,
      anon_sym_POUND_LBRACE,
    ACTIONS(170), 1,
      aux_sym_interpolated_string_token1,
    ACTIONS(194), 1,
      anon_sym_DQUOTE,
    STATE(71), 1,
      aux_sym_interpolated_string_repeat1,
    ACTIONS(168), 3,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_POUND,
      anon_sym_BSLASH_BSLASH,
  [1823] = 5,
    ACTIONS(78), 1,
      anon_sym_LPAREN,
    ACTIONS(80), 1,
      anon_sym_LBRACK,
    ACTIONS(82), 1,
      anon_sym_DOT,
    STATE(41), 1,
      sym_arguments,
    ACTIONS(196), 3,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_TILDE_RBRACE_RBRACE,
  [1841] = 4,
    ACTIONS(198), 1,
      ts_builtin_sym_end,
    ACTIONS(200), 1,
      aux_sym_content_token1,
    STATE(70), 1,
      aux_sym_content_repeat1,
    ACTIONS(203), 4,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_DASH,
      anon_sym_LBRACE_LBRACE_TILDE,
      anon_sym_LBRACE_POUND,
  [1857] = 5,
    ACTIONS(205), 1,
      anon_sym_DQUOTE,
    ACTIONS(210), 1,
      aux_sym_interpolated_string_token1,
    ACTIONS(213), 1,
      anon_sym_POUND_LBRACE,
    STATE(71), 1,
      aux_sym_interpolated_string_repeat1,
    ACTIONS(207), 3,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_POUND,
      anon_sym_BSLASH_BSLASH,
  [1875] = 3,
    ACTIONS(88), 1,
      anon_sym_EQ_GT,
    ACTIONS(216), 1,
      anon_sym_EQ,
    ACTIONS(86), 5,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_DOT,
  [1889] = 5,
    ACTIONS(218), 1,
      anon_sym_LPAREN,
    ACTIONS(220), 1,
      anon_sym_LBRACK,
    ACTIONS(222), 1,
      anon_sym_DOT,
    STATE(110), 1,
      sym_arguments,
    ACTIONS(90), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1906] = 5,
    ACTIONS(78), 1,
      anon_sym_LPAREN,
    ACTIONS(80), 1,
      anon_sym_LBRACK,
    ACTIONS(82), 1,
      anon_sym_DOT,
    STATE(41), 1,
      sym_arguments,
    ACTIONS(224), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1923] = 2,
    ACTIONS(226), 1,
      ts_builtin_sym_end,
    ACTIONS(228), 5,
      aux_sym_content_token1,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_DASH,
      anon_sym_LBRACE_LBRACE_TILDE,
      anon_sym_LBRACE_POUND,
  [1934] = 5,
    ACTIONS(218), 1,
      anon_sym_LPAREN,
    ACTIONS(220), 1,
      anon_sym_LBRACK,
    ACTIONS(222), 1,
      anon_sym_DOT,
    STATE(110), 1,
      sym_arguments,
    ACTIONS(76), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1951] = 5,
    ACTIONS(78), 1,
      anon_sym_LPAREN,
    ACTIONS(80), 1,
      anon_sym_LBRACK,
    ACTIONS(82), 1,
      anon_sym_DOT,
    STATE(41), 1,
      sym_arguments,
    ACTIONS(230), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1968] = 2,
    ACTIONS(234), 1,
      aux_sym_interpolated_string_token1,
    ACTIONS(232), 5,
      anon_sym_DQUOTE,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_POUND,
      anon_sym_BSLASH_BSLASH,
      anon_sym_POUND_LBRACE,
  [1979] = 2,
    ACTIONS(236), 1,
      ts_builtin_sym_end,
    ACTIONS(238), 5,
      aux_sym_content_token1,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_DASH,
      anon_sym_LBRACE_LBRACE_TILDE,
      anon_sym_LBRACE_POUND,
  [1990] = 5,
    ACTIONS(218), 1,
      anon_sym_LPAREN,
    ACTIONS(220), 1,
      anon_sym_LBRACK,
    ACTIONS(222), 1,
      anon_sym_DOT,
    STATE(110), 1,
      sym_arguments,
    ACTIONS(240), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [2007] = 5,
    ACTIONS(78), 1,
      anon_sym_LPAREN,
    ACTIONS(80), 1,
      anon_sym_LBRACK,
    ACTIONS(82), 1,
      anon_sym_DOT,
    STATE(41), 1,
      sym_arguments,
    ACTIONS(242), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [2024] = 4,
    ACTIONS(88), 1,
      anon_sym_EQ_GT,
    ACTIONS(244), 1,
      anon_sym_RPAREN,
    ACTIONS(247), 1,
      anon_sym_COMMA,
    ACTIONS(86), 3,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_DOT,
  [2039] = 2,
    ACTIONS(249), 1,
      anon_sym_EQ_GT,
    ACTIONS(86), 5,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_DOT,
  [2050] = 5,
    ACTIONS(218), 1,
      anon_sym_LPAREN,
    ACTIONS(220), 1,
      anon_sym_LBRACK,
    ACTIONS(222), 1,
      anon_sym_DOT,
    STATE(111), 1,
      sym_arguments,
    ACTIONS(84), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [2067] = 3,
    ACTIONS(88), 1,
      anon_sym_EQ_GT,
    ACTIONS(247), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
    ACTIONS(86), 3,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_DOT,
  [2080] = 1,
    ACTIONS(120), 5,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_DOT,
  [2088] = 1,
    ACTIONS(92), 5,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_DOT,
  [2096] = 5,
    ACTIONS(78), 1,
      anon_sym_LPAREN,
    ACTIONS(80), 1,
      anon_sym_LBRACK,
    ACTIONS(82), 1,
      anon_sym_DOT,
    ACTIONS(251), 1,
      anon_sym_RPAREN,
    STATE(41), 1,
      sym_arguments,
  [2112] = 5,
    ACTIONS(78), 1,
      anon_sym_LPAREN,
    ACTIONS(80), 1,
      anon_sym_LBRACK,
    ACTIONS(82), 1,
      anon_sym_DOT,
    ACTIONS(253), 1,
      anon_sym_RBRACK,
    STATE(41), 1,
      sym_arguments,
  [2128] = 3,
    ACTIONS(244), 1,
      anon_sym_RPAREN,
    ACTIONS(247), 1,
      anon_sym_COMMA,
    ACTIONS(86), 3,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_DOT,
  [2140] = 5,
    ACTIONS(78), 1,
      anon_sym_LPAREN,
    ACTIONS(80), 1,
      anon_sym_LBRACK,
    ACTIONS(82), 1,
      anon_sym_DOT,
    ACTIONS(255), 1,
      anon_sym_RPAREN,
    STATE(41), 1,
      sym_arguments,
  [2156] = 1,
    ACTIONS(122), 5,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_DOT,
  [2164] = 1,
    ACTIONS(118), 5,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_DOT,
  [2172] = 1,
    ACTIONS(112), 5,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_DOT,
  [2180] = 1,
    ACTIONS(98), 5,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_DOT,
  [2188] = 1,
    ACTIONS(102), 5,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_DOT,
  [2196] = 1,
    ACTIONS(108), 5,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_DOT,
  [2204] = 1,
    ACTIONS(110), 5,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_DOT,
  [2212] = 1,
    ACTIONS(116), 5,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_DOT,
  [2220] = 1,
    ACTIONS(106), 5,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_DOT,
  [2228] = 1,
    ACTIONS(86), 5,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_DOT,
  [2236] = 1,
    ACTIONS(124), 5,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_DOT,
  [2244] = 5,
    ACTIONS(78), 1,
      anon_sym_LPAREN,
    ACTIONS(80), 1,
      anon_sym_LBRACK,
    ACTIONS(82), 1,
      anon_sym_DOT,
    ACTIONS(257), 1,
      anon_sym_RBRACK,
    STATE(41), 1,
      sym_arguments,
  [2260] = 1,
    ACTIONS(126), 5,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_DOT,
  [2268] = 2,
    ACTIONS(247), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
    ACTIONS(86), 3,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_DOT,
  [2278] = 1,
    ACTIONS(128), 5,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_DOT,
  [2286] = 1,
    ACTIONS(96), 5,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_DOT,
  [2294] = 1,
    ACTIONS(100), 5,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_DOT,
  [2302] = 1,
    ACTIONS(104), 5,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_DOT,
  [2310] = 1,
    ACTIONS(114), 5,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_DOT,
  [2318] = 1,
    ACTIONS(114), 5,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_DOT,
  [2326] = 5,
    ACTIONS(78), 1,
      anon_sym_LPAREN,
    ACTIONS(80), 1,
      anon_sym_LBRACK,
    ACTIONS(82), 1,
      anon_sym_DOT,
    ACTIONS(259), 1,
      anon_sym_RPAREN,
    STATE(41), 1,
      sym_arguments,
  [2342] = 1,
    ACTIONS(94), 5,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_DOT,
  [2350] = 5,
    ACTIONS(218), 1,
      anon_sym_LPAREN,
    ACTIONS(220), 1,
      anon_sym_LBRACK,
    ACTIONS(222), 1,
      anon_sym_DOT,
    ACTIONS(261), 1,
      anon_sym_RBRACE,
    STATE(110), 1,
      sym_arguments,
  [2366] = 1,
    ACTIONS(130), 5,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_DOT,
  [2374] = 1,
    ACTIONS(132), 5,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_DOT,
  [2382] = 4,
    ACTIONS(78), 1,
      anon_sym_LPAREN,
    ACTIONS(80), 1,
      anon_sym_LBRACK,
    ACTIONS(82), 1,
      anon_sym_DOT,
    STATE(41), 1,
      sym_arguments,
  [2395] = 4,
    ACTIONS(263), 1,
      anon_sym_RBRACE,
    ACTIONS(265), 1,
      anon_sym_COMMA,
    ACTIONS(267), 1,
      anon_sym_COLON,
    STATE(133), 1,
      aux_sym_object_repeat1,
  [2408] = 4,
    ACTIONS(265), 1,
      anon_sym_COMMA,
    ACTIONS(267), 1,
      anon_sym_COLON,
    ACTIONS(269), 1,
      anon_sym_RBRACE,
    STATE(138), 1,
      aux_sym_object_repeat1,
  [2421] = 3,
    ACTIONS(265), 1,
      anon_sym_COMMA,
    ACTIONS(271), 1,
      anon_sym_RBRACE,
    STATE(136), 1,
      aux_sym_object_repeat1,
  [2431] = 2,
    ACTIONS(267), 1,
      anon_sym_COLON,
    ACTIONS(273), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [2439] = 3,
    ACTIONS(275), 1,
      anon_sym_RPAREN,
    ACTIONS(277), 1,
      anon_sym_COMMA,
    STATE(125), 1,
      aux_sym_formal_parameters_repeat1,
  [2449] = 3,
    ACTIONS(156), 1,
      anon_sym_COMMA,
    ACTIONS(279), 1,
      anon_sym_RPAREN,
    STATE(128), 1,
      aux_sym_arguments_repeat1,
  [2459] = 3,
    ACTIONS(281), 1,
      anon_sym_RBRACE,
    ACTIONS(283), 1,
      anon_sym_COMMA,
    STATE(124), 1,
      aux_sym_object_repeat1,
  [2469] = 3,
    ACTIONS(286), 1,
      anon_sym_RPAREN,
    ACTIONS(288), 1,
      anon_sym_COMMA,
    STATE(125), 1,
      aux_sym_formal_parameters_repeat1,
  [2479] = 3,
    ACTIONS(156), 1,
      anon_sym_COMMA,
    ACTIONS(291), 1,
      anon_sym_RPAREN,
    STATE(128), 1,
      aux_sym_arguments_repeat1,
  [2489] = 3,
    ACTIONS(224), 1,
      anon_sym_RBRACK,
    ACTIONS(293), 1,
      anon_sym_COMMA,
    STATE(127), 1,
      aux_sym_array_repeat1,
  [2499] = 3,
    ACTIONS(230), 1,
      anon_sym_RPAREN,
    ACTIONS(296), 1,
      anon_sym_COMMA,
    STATE(128), 1,
      aux_sym_arguments_repeat1,
  [2509] = 3,
    ACTIONS(156), 1,
      anon_sym_COMMA,
    ACTIONS(299), 1,
      anon_sym_RPAREN,
    STATE(128), 1,
      aux_sym_arguments_repeat1,
  [2519] = 3,
    ACTIONS(265), 1,
      anon_sym_COMMA,
    ACTIONS(301), 1,
      anon_sym_RBRACE,
    STATE(132), 1,
      aux_sym_object_repeat1,
  [2529] = 3,
    ACTIONS(277), 1,
      anon_sym_COMMA,
    ACTIONS(303), 1,
      anon_sym_RPAREN,
    STATE(122), 1,
      aux_sym_formal_parameters_repeat1,
  [2539] = 3,
    ACTIONS(265), 1,
      anon_sym_COMMA,
    ACTIONS(305), 1,
      anon_sym_RBRACE,
    STATE(124), 1,
      aux_sym_object_repeat1,
  [2549] = 3,
    ACTIONS(265), 1,
      anon_sym_COMMA,
    ACTIONS(307), 1,
      anon_sym_RBRACE,
    STATE(124), 1,
      aux_sym_object_repeat1,
  [2559] = 3,
    ACTIONS(158), 1,
      anon_sym_COMMA,
    ACTIONS(309), 1,
      anon_sym_RBRACK,
    STATE(127), 1,
      aux_sym_array_repeat1,
  [2569] = 3,
    ACTIONS(158), 1,
      anon_sym_COMMA,
    ACTIONS(311), 1,
      anon_sym_RBRACK,
    STATE(127), 1,
      aux_sym_array_repeat1,
  [2579] = 3,
    ACTIONS(265), 1,
      anon_sym_COMMA,
    ACTIONS(313), 1,
      anon_sym_RBRACE,
    STATE(124), 1,
      aux_sym_object_repeat1,
  [2589] = 3,
    ACTIONS(156), 1,
      anon_sym_COMMA,
    ACTIONS(315), 1,
      anon_sym_RPAREN,
    STATE(128), 1,
      aux_sym_arguments_repeat1,
  [2599] = 3,
    ACTIONS(265), 1,
      anon_sym_COMMA,
    ACTIONS(317), 1,
      anon_sym_RBRACE,
    STATE(124), 1,
      aux_sym_object_repeat1,
  [2609] = 1,
    ACTIONS(281), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [2614] = 1,
    ACTIONS(286), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [2619] = 1,
    ACTIONS(319), 1,
      sym_identifier,
  [2623] = 1,
    ACTIONS(321), 1,
      aux_sym_comment_token1,
  [2627] = 1,
    ACTIONS(323), 1,
      anon_sym_EQ_GT,
  [2631] = 1,
    ACTIONS(325), 1,
      anon_sym_COLON,
  [2635] = 1,
    ACTIONS(327), 1,
      sym_identifier,
  [2639] = 1,
    ACTIONS(329), 1,
      anon_sym_EQ_GT,
  [2643] = 1,
    ACTIONS(331), 1,
      anon_sym_COLON,
  [2647] = 1,
    ACTIONS(333), 1,
      anon_sym_EQ_GT,
  [2651] = 1,
    ACTIONS(335), 1,
      anon_sym_EQ_GT,
  [2655] = 1,
    ACTIONS(337), 1,
      anon_sym_RBRACE,
  [2659] = 1,
    ACTIONS(339), 1,
      anon_sym_EQ_GT,
  [2663] = 1,
    ACTIONS(341), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 57,
  [SMALL_STATE(4)] = 114,
  [SMALL_STATE(5)] = 166,
  [SMALL_STATE(6)] = 218,
  [SMALL_STATE(7)] = 270,
  [SMALL_STATE(8)] = 322,
  [SMALL_STATE(9)] = 376,
  [SMALL_STATE(10)] = 425,
  [SMALL_STATE(11)] = 474,
  [SMALL_STATE(12)] = 523,
  [SMALL_STATE(13)] = 572,
  [SMALL_STATE(14)] = 621,
  [SMALL_STATE(15)] = 670,
  [SMALL_STATE(16)] = 719,
  [SMALL_STATE(17)] = 768,
  [SMALL_STATE(18)] = 817,
  [SMALL_STATE(19)] = 866,
  [SMALL_STATE(20)] = 915,
  [SMALL_STATE(21)] = 964,
  [SMALL_STATE(22)] = 1013,
  [SMALL_STATE(23)] = 1062,
  [SMALL_STATE(24)] = 1111,
  [SMALL_STATE(25)] = 1136,
  [SMALL_STATE(26)] = 1161,
  [SMALL_STATE(27)] = 1182,
  [SMALL_STATE(28)] = 1203,
  [SMALL_STATE(29)] = 1218,
  [SMALL_STATE(30)] = 1239,
  [SMALL_STATE(31)] = 1251,
  [SMALL_STATE(32)] = 1263,
  [SMALL_STATE(33)] = 1275,
  [SMALL_STATE(34)] = 1287,
  [SMALL_STATE(35)] = 1299,
  [SMALL_STATE(36)] = 1311,
  [SMALL_STATE(37)] = 1323,
  [SMALL_STATE(38)] = 1335,
  [SMALL_STATE(39)] = 1347,
  [SMALL_STATE(40)] = 1359,
  [SMALL_STATE(41)] = 1371,
  [SMALL_STATE(42)] = 1383,
  [SMALL_STATE(43)] = 1395,
  [SMALL_STATE(44)] = 1407,
  [SMALL_STATE(45)] = 1419,
  [SMALL_STATE(46)] = 1431,
  [SMALL_STATE(47)] = 1443,
  [SMALL_STATE(48)] = 1455,
  [SMALL_STATE(49)] = 1467,
  [SMALL_STATE(50)] = 1479,
  [SMALL_STATE(51)] = 1491,
  [SMALL_STATE(52)] = 1503,
  [SMALL_STATE(53)] = 1515,
  [SMALL_STATE(54)] = 1536,
  [SMALL_STATE(55)] = 1557,
  [SMALL_STATE(56)] = 1575,
  [SMALL_STATE(57)] = 1597,
  [SMALL_STATE(58)] = 1619,
  [SMALL_STATE(59)] = 1637,
  [SMALL_STATE(60)] = 1659,
  [SMALL_STATE(61)] = 1677,
  [SMALL_STATE(62)] = 1699,
  [SMALL_STATE(63)] = 1717,
  [SMALL_STATE(64)] = 1731,
  [SMALL_STATE(65)] = 1745,
  [SMALL_STATE(66)] = 1767,
  [SMALL_STATE(67)] = 1783,
  [SMALL_STATE(68)] = 1805,
  [SMALL_STATE(69)] = 1823,
  [SMALL_STATE(70)] = 1841,
  [SMALL_STATE(71)] = 1857,
  [SMALL_STATE(72)] = 1875,
  [SMALL_STATE(73)] = 1889,
  [SMALL_STATE(74)] = 1906,
  [SMALL_STATE(75)] = 1923,
  [SMALL_STATE(76)] = 1934,
  [SMALL_STATE(77)] = 1951,
  [SMALL_STATE(78)] = 1968,
  [SMALL_STATE(79)] = 1979,
  [SMALL_STATE(80)] = 1990,
  [SMALL_STATE(81)] = 2007,
  [SMALL_STATE(82)] = 2024,
  [SMALL_STATE(83)] = 2039,
  [SMALL_STATE(84)] = 2050,
  [SMALL_STATE(85)] = 2067,
  [SMALL_STATE(86)] = 2080,
  [SMALL_STATE(87)] = 2088,
  [SMALL_STATE(88)] = 2096,
  [SMALL_STATE(89)] = 2112,
  [SMALL_STATE(90)] = 2128,
  [SMALL_STATE(91)] = 2140,
  [SMALL_STATE(92)] = 2156,
  [SMALL_STATE(93)] = 2164,
  [SMALL_STATE(94)] = 2172,
  [SMALL_STATE(95)] = 2180,
  [SMALL_STATE(96)] = 2188,
  [SMALL_STATE(97)] = 2196,
  [SMALL_STATE(98)] = 2204,
  [SMALL_STATE(99)] = 2212,
  [SMALL_STATE(100)] = 2220,
  [SMALL_STATE(101)] = 2228,
  [SMALL_STATE(102)] = 2236,
  [SMALL_STATE(103)] = 2244,
  [SMALL_STATE(104)] = 2260,
  [SMALL_STATE(105)] = 2268,
  [SMALL_STATE(106)] = 2278,
  [SMALL_STATE(107)] = 2286,
  [SMALL_STATE(108)] = 2294,
  [SMALL_STATE(109)] = 2302,
  [SMALL_STATE(110)] = 2310,
  [SMALL_STATE(111)] = 2318,
  [SMALL_STATE(112)] = 2326,
  [SMALL_STATE(113)] = 2342,
  [SMALL_STATE(114)] = 2350,
  [SMALL_STATE(115)] = 2366,
  [SMALL_STATE(116)] = 2374,
  [SMALL_STATE(117)] = 2382,
  [SMALL_STATE(118)] = 2395,
  [SMALL_STATE(119)] = 2408,
  [SMALL_STATE(120)] = 2421,
  [SMALL_STATE(121)] = 2431,
  [SMALL_STATE(122)] = 2439,
  [SMALL_STATE(123)] = 2449,
  [SMALL_STATE(124)] = 2459,
  [SMALL_STATE(125)] = 2469,
  [SMALL_STATE(126)] = 2479,
  [SMALL_STATE(127)] = 2489,
  [SMALL_STATE(128)] = 2499,
  [SMALL_STATE(129)] = 2509,
  [SMALL_STATE(130)] = 2519,
  [SMALL_STATE(131)] = 2529,
  [SMALL_STATE(132)] = 2539,
  [SMALL_STATE(133)] = 2549,
  [SMALL_STATE(134)] = 2559,
  [SMALL_STATE(135)] = 2569,
  [SMALL_STATE(136)] = 2579,
  [SMALL_STATE(137)] = 2589,
  [SMALL_STATE(138)] = 2599,
  [SMALL_STATE(139)] = 2609,
  [SMALL_STATE(140)] = 2614,
  [SMALL_STATE(141)] = 2619,
  [SMALL_STATE(142)] = 2623,
  [SMALL_STATE(143)] = 2627,
  [SMALL_STATE(144)] = 2631,
  [SMALL_STATE(145)] = 2635,
  [SMALL_STATE(146)] = 2639,
  [SMALL_STATE(147)] = 2643,
  [SMALL_STATE(148)] = 2647,
  [SMALL_STATE(149)] = 2651,
  [SMALL_STATE(150)] = 2655,
  [SMALL_STATE(151)] = 2659,
  [SMALL_STATE(152)] = 2663,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(142),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(149),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(85),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(100),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(102),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2),
  [65] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_template_repeat1, 2), SHIFT_REPEAT(66),
  [68] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_template_repeat1, 2), SHIFT_REPEAT(16),
  [71] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_template_repeat1, 2), SHIFT_REPEAT(142),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template, 1),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arrow_function, 3, .production_id = 6),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(145),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primary_expression, 1),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arrow_function, 3, .production_id = 3),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 2),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 3, .production_id = 4),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interpolated_string, 2),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subscript_expression, 4, .production_id = 8),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 2),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 3),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 2),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_null, 1),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 4),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 4, .production_id = 4),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 4),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_expression, 2, .production_id = 2),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 4),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 5),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parenthesized_expression, 3),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 6),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_member_expression, 3, .production_id = 5),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 3),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interpolated_string, 3),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 3),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(144),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [146] = {.entry = {.count = 1, .reusable = false}}, SHIFT(107),
  [148] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [152] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [166] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [168] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [174] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [176] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [180] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [182] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_content, 1),
  [188] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [190] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_content, 1),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [194] = {.entry = {.count = 1, .reusable = false}}, SHIFT(115),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_content_repeat1, 2),
  [200] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_content_repeat1, 2), SHIFT_REPEAT(70),
  [203] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_content_repeat1, 2),
  [205] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_interpolated_string_repeat1, 2),
  [207] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_interpolated_string_repeat1, 2), SHIFT_REPEAT(71),
  [210] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_interpolated_string_repeat1, 2), SHIFT_REPEAT(71),
  [213] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_interpolated_string_repeat1, 2), SHIFT_REPEAT(22),
  [216] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(141),
  [224] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3),
  [228] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 3),
  [230] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_arguments_repeat1, 2),
  [232] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_interpolated_string_repeat1, 3),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_interpolated_string_repeat1, 3),
  [236] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_output_directive, 3),
  [238] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_output_directive, 3),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pair, 3, .production_id = 7),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_arguments_repeat1, 4),
  [244] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_primary_expression, 1), REDUCE(sym_pattern, 1, .dynamic_precedence = -1),
  [247] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern, 1, .dynamic_precedence = -1),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(147),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [267] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__property_name, 1, .production_id = 1),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [273] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_object_repeat1, 2, .production_id = 4),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(148),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [281] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_object_repeat1, 2),
  [283] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_object_repeat1, 2), SHIFT_REPEAT(58),
  [286] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_formal_parameters_repeat1, 2),
  [288] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_formal_parameters_repeat1, 2), SHIFT_REPEAT(8),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [293] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(14),
  [296] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_arguments_repeat1, 2), SHIFT_REPEAT(21),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(146),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(150),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [329] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_formal_parameters, 3),
  [331] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_computed_property_name, 3),
  [333] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_formal_parameters, 4),
  [335] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_formal_parameters, 2),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [339] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [341] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_twig(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
