#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 135
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 62
#define ALIAS_COUNT 1
#define TOKEN_COUNT 33
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 10
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 9

enum {
  sym_identifier = 1,
  aux_sym_content_token1 = 2,
  anon_sym_LBRACE_LBRACE = 3,
  anon_sym_LBRACE_LBRACE_DASH = 4,
  anon_sym_LBRACE_LBRACE_TILDE = 5,
  anon_sym_RBRACE_RBRACE = 6,
  anon_sym_DASH_RBRACE_RBRACE = 7,
  anon_sym_TILDE_RBRACE_RBRACE = 8,
  anon_sym_LBRACE_POUND = 9,
  aux_sym_comment_token1 = 10,
  anon_sym_RBRACE = 11,
  anon_sym_LPAREN = 12,
  anon_sym_RPAREN = 13,
  anon_sym_null = 14,
  anon_sym_none = 15,
  sym_number = 16,
  anon_sym_true = 17,
  anon_sym_false = 18,
  sym_string = 19,
  anon_sym_DQUOTE = 20,
  anon_sym_BSLASH_DQUOTE = 21,
  anon_sym_BSLASH_POUND = 22,
  anon_sym_BSLASH_BSLASH = 23,
  aux_sym_interpolated_string_token1 = 24,
  anon_sym_POUND_LBRACE = 25,
  anon_sym_LBRACK = 26,
  anon_sym_COMMA = 27,
  anon_sym_RBRACK = 28,
  anon_sym_LBRACE = 29,
  anon_sym_COLON = 30,
  anon_sym_EQ_GT = 31,
  anon_sym_DOT = 32,
  sym_template = 33,
  sym__source_element = 34,
  sym_content = 35,
  sym_output_directive = 36,
  sym_comment = 37,
  sym_expression = 38,
  sym_primary_expression = 39,
  sym_parenthesized_expression = 40,
  sym_null = 41,
  sym_boolean = 42,
  sym_interpolated_string = 43,
  sym_array = 44,
  sym_object = 45,
  sym_pair = 46,
  sym__property_name = 47,
  sym_computed_property_name = 48,
  sym_arrow_function = 49,
  sym_formal_parameters = 50,
  sym_pattern = 51,
  sym_member_expression = 52,
  sym_subscript_expression = 53,
  sym_call_expression = 54,
  sym_arguments = 55,
  aux_sym_template_repeat1 = 56,
  aux_sym_content_repeat1 = 57,
  aux_sym_interpolated_string_repeat1 = 58,
  aux_sym_array_repeat1 = 59,
  aux_sym_object_repeat1 = 60,
  aux_sym_formal_parameters_repeat1 = 61,
  alias_sym_property_identifier = 62,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [aux_sym_content_token1] = "content_token1",
  [anon_sym_LBRACE_LBRACE] = "{{",
  [anon_sym_LBRACE_LBRACE_DASH] = "{{-",
  [anon_sym_LBRACE_LBRACE_TILDE] = "{{~",
  [anon_sym_RBRACE_RBRACE] = "}}",
  [anon_sym_DASH_RBRACE_RBRACE] = "-}}",
  [anon_sym_TILDE_RBRACE_RBRACE] = "~}}",
  [anon_sym_LBRACE_POUND] = "{#",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_null] = "null",
  [anon_sym_none] = "none",
  [sym_number] = "number",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_string] = "string",
  [anon_sym_DQUOTE] = "\"",
  [anon_sym_BSLASH_DQUOTE] = "\\\"",
  [anon_sym_BSLASH_POUND] = "\\#",
  [anon_sym_BSLASH_BSLASH] = "\\\\",
  [aux_sym_interpolated_string_token1] = "interpolated_string_token1",
  [anon_sym_POUND_LBRACE] = "#{",
  [anon_sym_LBRACK] = "[",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LBRACE] = "{",
  [anon_sym_COLON] = ":",
  [anon_sym_EQ_GT] = "=>",
  [anon_sym_DOT] = ".",
  [sym_template] = "template",
  [sym__source_element] = "_source_element",
  [sym_content] = "content",
  [sym_output_directive] = "output_directive",
  [sym_comment] = "comment",
  [sym_expression] = "expression",
  [sym_primary_expression] = "primary_expression",
  [sym_parenthesized_expression] = "parenthesized_expression",
  [sym_null] = "null",
  [sym_boolean] = "boolean",
  [sym_interpolated_string] = "interpolated_string",
  [sym_array] = "array",
  [sym_object] = "object",
  [sym_pair] = "pair",
  [sym__property_name] = "_property_name",
  [sym_computed_property_name] = "computed_property_name",
  [sym_arrow_function] = "arrow_function",
  [sym_formal_parameters] = "formal_parameters",
  [sym_pattern] = "pattern",
  [sym_member_expression] = "member_expression",
  [sym_subscript_expression] = "subscript_expression",
  [sym_call_expression] = "call_expression",
  [sym_arguments] = "arguments",
  [aux_sym_template_repeat1] = "template_repeat1",
  [aux_sym_content_repeat1] = "content_repeat1",
  [aux_sym_interpolated_string_repeat1] = "interpolated_string_repeat1",
  [aux_sym_array_repeat1] = "array_repeat1",
  [aux_sym_object_repeat1] = "object_repeat1",
  [aux_sym_formal_parameters_repeat1] = "formal_parameters_repeat1",
  [alias_sym_property_identifier] = "property_identifier",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [aux_sym_content_token1] = aux_sym_content_token1,
  [anon_sym_LBRACE_LBRACE] = anon_sym_LBRACE_LBRACE,
  [anon_sym_LBRACE_LBRACE_DASH] = anon_sym_LBRACE_LBRACE_DASH,
  [anon_sym_LBRACE_LBRACE_TILDE] = anon_sym_LBRACE_LBRACE_TILDE,
  [anon_sym_RBRACE_RBRACE] = anon_sym_RBRACE_RBRACE,
  [anon_sym_DASH_RBRACE_RBRACE] = anon_sym_DASH_RBRACE_RBRACE,
  [anon_sym_TILDE_RBRACE_RBRACE] = anon_sym_TILDE_RBRACE_RBRACE,
  [anon_sym_LBRACE_POUND] = anon_sym_LBRACE_POUND,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_null] = anon_sym_null,
  [anon_sym_none] = anon_sym_none,
  [sym_number] = sym_number,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_string] = sym_string,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [anon_sym_BSLASH_DQUOTE] = anon_sym_BSLASH_DQUOTE,
  [anon_sym_BSLASH_POUND] = anon_sym_BSLASH_POUND,
  [anon_sym_BSLASH_BSLASH] = anon_sym_BSLASH_BSLASH,
  [aux_sym_interpolated_string_token1] = aux_sym_interpolated_string_token1,
  [anon_sym_POUND_LBRACE] = anon_sym_POUND_LBRACE,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_EQ_GT] = anon_sym_EQ_GT,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_template] = sym_template,
  [sym__source_element] = sym__source_element,
  [sym_content] = sym_content,
  [sym_output_directive] = sym_output_directive,
  [sym_comment] = sym_comment,
  [sym_expression] = sym_expression,
  [sym_primary_expression] = sym_primary_expression,
  [sym_parenthesized_expression] = sym_parenthesized_expression,
  [sym_null] = sym_null,
  [sym_boolean] = sym_boolean,
  [sym_interpolated_string] = sym_interpolated_string,
  [sym_array] = sym_array,
  [sym_object] = sym_object,
  [sym_pair] = sym_pair,
  [sym__property_name] = sym__property_name,
  [sym_computed_property_name] = sym_computed_property_name,
  [sym_arrow_function] = sym_arrow_function,
  [sym_formal_parameters] = sym_formal_parameters,
  [sym_pattern] = sym_pattern,
  [sym_member_expression] = sym_member_expression,
  [sym_subscript_expression] = sym_subscript_expression,
  [sym_call_expression] = sym_call_expression,
  [sym_arguments] = sym_arguments,
  [aux_sym_template_repeat1] = aux_sym_template_repeat1,
  [aux_sym_content_repeat1] = aux_sym_content_repeat1,
  [aux_sym_interpolated_string_repeat1] = aux_sym_interpolated_string_repeat1,
  [aux_sym_array_repeat1] = aux_sym_array_repeat1,
  [aux_sym_object_repeat1] = aux_sym_object_repeat1,
  [aux_sym_formal_parameters_repeat1] = aux_sym_formal_parameters_repeat1,
  [alias_sym_property_identifier] = alias_sym_property_identifier,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_content_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACE_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_LBRACE_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_LBRACE_TILDE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_RBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TILDE_RBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_POUND] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_null] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_none] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_interpolated_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_POUND_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_template] = {
    .visible = true,
    .named = true,
  },
  [sym__source_element] = {
    .visible = false,
    .named = true,
  },
  [sym_content] = {
    .visible = true,
    .named = true,
  },
  [sym_output_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_primary_expression] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_parenthesized_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_null] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_interpolated_string] = {
    .visible = true,
    .named = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [sym_object] = {
    .visible = true,
    .named = true,
  },
  [sym_pair] = {
    .visible = true,
    .named = true,
  },
  [sym__property_name] = {
    .visible = false,
    .named = true,
  },
  [sym_computed_property_name] = {
    .visible = true,
    .named = true,
  },
  [sym_arrow_function] = {
    .visible = true,
    .named = true,
  },
  [sym_formal_parameters] = {
    .visible = true,
    .named = true,
  },
  [sym_pattern] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_member_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_subscript_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_call_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_arguments] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_template_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_content_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_interpolated_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_object_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_formal_parameters_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_property_identifier] = {
    .visible = true,
    .named = true,
  },
};

enum {
  field_arguments = 1,
  field_body = 2,
  field_function = 3,
  field_index = 4,
  field_key = 5,
  field_object = 6,
  field_parameter = 7,
  field_parameters = 8,
  field_property = 9,
  field_value = 10,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_arguments] = "arguments",
  [field_body] = "body",
  [field_function] = "function",
  [field_index] = "index",
  [field_key] = "key",
  [field_object] = "object",
  [field_parameter] = "parameter",
  [field_parameters] = "parameters",
  [field_property] = "property",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [2] = {.index = 0, .length = 2},
  [3] = {.index = 2, .length = 2},
  [5] = {.index = 4, .length = 2},
  [6] = {.index = 6, .length = 2},
  [7] = {.index = 8, .length = 2},
  [8] = {.index = 10, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_arguments, 1},
    {field_function, 0},
  [2] =
    {field_body, 2},
    {field_parameter, 0},
  [4] =
    {field_object, 0},
    {field_property, 2},
  [6] =
    {field_body, 2},
    {field_parameters, 0},
  [8] =
    {field_key, 0},
    {field_value, 2},
  [10] =
    {field_index, 2},
    {field_object, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = sym_string,
  },
  [4] = {
    [1] = sym_string,
  },
  [5] = {
    [2] = alias_sym_property_identifier,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 2,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 4,
  [8] = 5,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 11,
  [13] = 13,
  [14] = 9,
  [15] = 15,
  [16] = 16,
  [17] = 10,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 47,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 53,
  [56] = 49,
  [57] = 57,
  [58] = 58,
  [59] = 54,
  [60] = 60,
  [61] = 61,
  [62] = 58,
  [63] = 63,
  [64] = 63,
  [65] = 65,
  [66] = 23,
  [67] = 22,
  [68] = 68,
  [69] = 24,
  [70] = 25,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 39,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 76,
  [79] = 36,
  [80] = 34,
  [81] = 31,
  [82] = 28,
  [83] = 29,
  [84] = 30,
  [85] = 75,
  [86] = 26,
  [87] = 32,
  [88] = 33,
  [89] = 43,
  [90] = 44,
  [91] = 91,
  [92] = 35,
  [93] = 77,
  [94] = 37,
  [95] = 38,
  [96] = 40,
  [97] = 42,
  [98] = 46,
  [99] = 27,
  [100] = 41,
  [101] = 45,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 103,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 106,
  [111] = 109,
  [112] = 108,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 114,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 117,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 124,
  [127] = 127,
  [128] = 128,
  [129] = 127,
  [130] = 130,
  [131] = 131,
  [132] = 132,
  [133] = 133,
  [134] = 134,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(21);
      if (lookahead == '"') ADVANCE(42);
      if (lookahead == '#') ADVANCE(9);
      if (lookahead == '\'') ADVANCE(7);
      if (lookahead == '(') ADVANCE(34);
      if (lookahead == ')') ADVANCE(35);
      if (lookahead == ',') ADVANCE(50);
      if (lookahead == '-') ADVANCE(13);
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == ':') ADVANCE(54);
      if (lookahead == '=') ADVANCE(8);
      if (lookahead == '[') ADVANCE(49);
      if (lookahead == '\\') ADVANCE(3);
      if (lookahead == ']') ADVANCE(51);
      if (lookahead == '{') ADVANCE(53);
      if (lookahead == '}') ADVANCE(33);
      if (lookahead == '~') ADVANCE(14);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (127 <= lookahead && lookahead <= 255)) ADVANCE(36);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(42);
      if (lookahead == '\'') ADVANCE(7);
      if (lookahead == '(') ADVANCE(34);
      if (lookahead == ')') ADVANCE(35);
      if (lookahead == ',') ADVANCE(50);
      if (lookahead == '-') ADVANCE(13);
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == '=') ADVANCE(8);
      if (lookahead == '[') ADVANCE(49);
      if (lookahead == ']') ADVANCE(51);
      if (lookahead == '{') ADVANCE(52);
      if (lookahead == '}') ADVANCE(12);
      if (lookahead == '~') ADVANCE(14);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (127 <= lookahead && lookahead <= 255)) ADVANCE(36);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(40);
      if (lookahead == '\\') ADVANCE(19);
      if (lookahead != 0 &&
          lookahead != '#') ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(43);
      if (lookahead == '#') ADVANCE(44);
      if (lookahead == '\\') ADVANCE(45);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(41);
      if (lookahead == '#') ADVANCE(9);
      if (lookahead == '\\') ADVANCE(3);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(46);
      if (lookahead != 0) ADVANCE(47);
      END_STATE();
    case 5:
      if (lookahead == '#') ADVANCE(32);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(5);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 6:
      if (lookahead == '#') ADVANCE(32);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == '\'') ADVANCE(40);
      if (lookahead == '\\') ADVANCE(18);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 8:
      if (lookahead == '>') ADVANCE(55);
      END_STATE();
    case 9:
      if (lookahead == '{') ADVANCE(48);
      END_STATE();
    case 10:
      if (lookahead == '}') ADVANCE(29);
      END_STATE();
    case 11:
      if (lookahead == '}') ADVANCE(30);
      END_STATE();
    case 12:
      if (lookahead == '}') ADVANCE(28);
      END_STATE();
    case 13:
      if (lookahead == '}') ADVANCE(10);
      END_STATE();
    case 14:
      if (lookahead == '}') ADVANCE(11);
      END_STATE();
    case 15:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(17);
      END_STATE();
    case 16:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(38);
      END_STATE();
    case 17:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      END_STATE();
    case 18:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(7);
      END_STATE();
    case 19:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 20:
      if (eof) ADVANCE(21);
      if (lookahead == '{') ADVANCE(22);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(23);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_content_token1);
      if (lookahead == '#') ADVANCE(31);
      if (lookahead == '{') ADVANCE(25);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_content_token1);
      if (lookahead == '{') ADVANCE(22);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(23);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_content_token1);
      if (lookahead != 0 &&
          lookahead != '{') ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE);
      if (lookahead == '-') ADVANCE(26);
      if (lookahead == '~') ADVANCE(27);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE_DASH);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE_TILDE);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_RBRACE_RBRACE);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_DASH_RBRACE_RBRACE);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_TILDE_RBRACE_RBRACE);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_LBRACE_POUND);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '#') ADVANCE(32);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(6);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (127 <= lookahead && lookahead <= 255)) ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(16);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      if (lookahead == '"') ADVANCE(40);
      if (lookahead == '\\') ADVANCE(19);
      if (lookahead != 0 &&
          lookahead != '#') ADVANCE(2);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_BSLASH_DQUOTE);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_BSLASH_POUND);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_BSLASH_BSLASH);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_interpolated_string_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(46);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '\\') ADVANCE(47);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_interpolated_string_token1);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '\\') ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_POUND_LBRACE);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead == '#') ADVANCE(31);
      if (lookahead == '{') ADVANCE(25);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_EQ_GT);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'f') ADVANCE(1);
      if (lookahead == 'n') ADVANCE(2);
      if (lookahead == 't') ADVANCE(3);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == 'a') ADVANCE(4);
      END_STATE();
    case 2:
      if (lookahead == 'o') ADVANCE(5);
      if (lookahead == 'u') ADVANCE(6);
      END_STATE();
    case 3:
      if (lookahead == 'r') ADVANCE(7);
      END_STATE();
    case 4:
      if (lookahead == 'l') ADVANCE(8);
      END_STATE();
    case 5:
      if (lookahead == 'n') ADVANCE(9);
      END_STATE();
    case 6:
      if (lookahead == 'l') ADVANCE(10);
      END_STATE();
    case 7:
      if (lookahead == 'u') ADVANCE(11);
      END_STATE();
    case 8:
      if (lookahead == 's') ADVANCE(12);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(13);
      END_STATE();
    case 10:
      if (lookahead == 'l') ADVANCE(14);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(15);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(16);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_none);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_null);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 20},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 20},
  [21] = {.lex_state = 20},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 20},
  [53] = {.lex_state = 4},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 4},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 4},
  [58] = {.lex_state = 4},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 20},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 4},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 20},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 20},
  [72] = {.lex_state = 4},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 5},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 0},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 0},
  [131] = {.lex_state = 0},
  [132] = {.lex_state = 0},
  [133] = {.lex_state = 0},
  [134] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACE_DASH] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACE_TILDE] = ACTIONS(1),
    [anon_sym_DASH_RBRACE_RBRACE] = ACTIONS(1),
    [anon_sym_TILDE_RBRACE_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACE_POUND] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_null] = ACTIONS(1),
    [anon_sym_none] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_BSLASH_DQUOTE] = ACTIONS(1),
    [anon_sym_BSLASH_POUND] = ACTIONS(1),
    [anon_sym_BSLASH_BSLASH] = ACTIONS(1),
    [anon_sym_POUND_LBRACE] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_EQ_GT] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
  },
  [1] = {
    [sym_template] = STATE(134),
    [sym__source_element] = STATE(20),
    [sym_content] = STATE(20),
    [sym_output_directive] = STATE(20),
    [sym_comment] = STATE(20),
    [aux_sym_template_repeat1] = STATE(20),
    [aux_sym_content_repeat1] = STATE(52),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym_content_token1] = ACTIONS(5),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(7),
    [anon_sym_LBRACE_LBRACE_DASH] = ACTIONS(7),
    [anon_sym_LBRACE_LBRACE_TILDE] = ACTIONS(7),
    [anon_sym_LBRACE_POUND] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 15,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_RPAREN,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_LBRACE,
    STATE(22), 1,
      sym_primary_expression,
    STATE(78), 1,
      sym_expression,
    STATE(107), 1,
      sym_pattern,
    STATE(129), 1,
      sym_formal_parameters,
    ACTIONS(17), 2,
      anon_sym_null,
      anon_sym_none,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(77), 2,
      sym_member_expression,
      sym_subscript_expression,
    STATE(43), 8,
      sym_parenthesized_expression,
      sym_null,
      sym_boolean,
      sym_interpolated_string,
      sym_array,
      sym_object,
      sym_arrow_function,
      sym_call_expression,
  [57] = 15,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_RPAREN,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_LBRACE,
    STATE(22), 1,
      sym_primary_expression,
    STATE(76), 1,
      sym_expression,
    STATE(107), 1,
      sym_pattern,
    STATE(129), 1,
      sym_formal_parameters,
    ACTIONS(17), 2,
      anon_sym_null,
      anon_sym_none,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(77), 2,
      sym_member_expression,
      sym_subscript_expression,
    STATE(43), 8,
      sym_parenthesized_expression,
      sym_null,
      sym_boolean,
      sym_interpolated_string,
      sym_array,
      sym_object,
      sym_arrow_function,
      sym_call_expression,
  [114] = 13,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_LBRACE,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(31), 1,
      anon_sym_RPAREN,
    STATE(22), 1,
      sym_primary_expression,
    STATE(59), 1,
      sym_expression,
    STATE(129), 1,
      sym_formal_parameters,
    ACTIONS(17), 2,
      anon_sym_null,
      anon_sym_none,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(43), 10,
      sym_parenthesized_expression,
      sym_null,
      sym_boolean,
      sym_interpolated_string,
      sym_array,
      sym_object,
      sym_arrow_function,
      sym_member_expression,
      sym_subscript_expression,
      sym_call_expression,
  [166] = 13,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_LBRACE,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(33), 1,
      anon_sym_RBRACK,
    STATE(22), 1,
      sym_primary_expression,
    STATE(49), 1,
      sym_expression,
    STATE(129), 1,
      sym_formal_parameters,
    ACTIONS(17), 2,
      anon_sym_null,
      anon_sym_none,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(43), 10,
      sym_parenthesized_expression,
      sym_null,
      sym_boolean,
      sym_interpolated_string,
      sym_array,
      sym_object,
      sym_arrow_function,
      sym_member_expression,
      sym_subscript_expression,
      sym_call_expression,
  [218] = 14,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_LBRACE,
    ACTIONS(35), 1,
      sym_identifier,
    STATE(22), 1,
      sym_primary_expression,
    STATE(102), 1,
      sym_expression,
    STATE(122), 1,
      sym_pattern,
    STATE(129), 1,
      sym_formal_parameters,
    ACTIONS(17), 2,
      anon_sym_null,
      anon_sym_none,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(93), 2,
      sym_member_expression,
      sym_subscript_expression,
    STATE(43), 8,
      sym_parenthesized_expression,
      sym_null,
      sym_boolean,
      sym_interpolated_string,
      sym_array,
      sym_object,
      sym_arrow_function,
      sym_call_expression,
  [272] = 13,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_LBRACE,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(37), 1,
      anon_sym_RPAREN,
    STATE(22), 1,
      sym_primary_expression,
    STATE(54), 1,
      sym_expression,
    STATE(129), 1,
      sym_formal_parameters,
    ACTIONS(17), 2,
      anon_sym_null,
      anon_sym_none,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(43), 10,
      sym_parenthesized_expression,
      sym_null,
      sym_boolean,
      sym_interpolated_string,
      sym_array,
      sym_object,
      sym_arrow_function,
      sym_member_expression,
      sym_subscript_expression,
      sym_call_expression,
  [324] = 13,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_LBRACE,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(39), 1,
      anon_sym_RBRACK,
    STATE(22), 1,
      sym_primary_expression,
    STATE(56), 1,
      sym_expression,
    STATE(129), 1,
      sym_formal_parameters,
    ACTIONS(17), 2,
      anon_sym_null,
      anon_sym_none,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(43), 10,
      sym_parenthesized_expression,
      sym_null,
      sym_boolean,
      sym_interpolated_string,
      sym_array,
      sym_object,
      sym_arrow_function,
      sym_member_expression,
      sym_subscript_expression,
      sym_call_expression,
  [376] = 12,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_LBRACE,
    ACTIONS(29), 1,
      sym_identifier,
    STATE(22), 1,
      sym_primary_expression,
    STATE(85), 1,
      sym_expression,
    STATE(129), 1,
      sym_formal_parameters,
    ACTIONS(17), 2,
      anon_sym_null,
      anon_sym_none,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(43), 10,
      sym_parenthesized_expression,
      sym_null,
      sym_boolean,
      sym_interpolated_string,
      sym_array,
      sym_object,
      sym_arrow_function,
      sym_member_expression,
      sym_subscript_expression,
      sym_call_expression,
  [425] = 12,
    ACTIONS(41), 1,
      sym_identifier,
    ACTIONS(43), 1,
      anon_sym_LPAREN,
    ACTIONS(51), 1,
      anon_sym_DQUOTE,
    ACTIONS(53), 1,
      anon_sym_LBRACK,
    ACTIONS(55), 1,
      anon_sym_LBRACE,
    STATE(67), 1,
      sym_primary_expression,
    STATE(70), 1,
      sym_expression,
    STATE(127), 1,
      sym_formal_parameters,
    ACTIONS(45), 2,
      anon_sym_null,
      anon_sym_none,
    ACTIONS(47), 2,
      sym_number,
      sym_string,
    ACTIONS(49), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(89), 10,
      sym_parenthesized_expression,
      sym_null,
      sym_boolean,
      sym_interpolated_string,
      sym_array,
      sym_object,
      sym_arrow_function,
      sym_member_expression,
      sym_subscript_expression,
      sym_call_expression,
  [474] = 12,
    ACTIONS(41), 1,
      sym_identifier,
    ACTIONS(43), 1,
      anon_sym_LPAREN,
    ACTIONS(51), 1,
      anon_sym_DQUOTE,
    ACTIONS(53), 1,
      anon_sym_LBRACK,
    ACTIONS(55), 1,
      anon_sym_LBRACE,
    STATE(67), 1,
      sym_primary_expression,
    STATE(69), 1,
      sym_expression,
    STATE(127), 1,
      sym_formal_parameters,
    ACTIONS(45), 2,
      anon_sym_null,
      anon_sym_none,
    ACTIONS(47), 2,
      sym_number,
      sym_string,
    ACTIONS(49), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(89), 10,
      sym_parenthesized_expression,
      sym_null,
      sym_boolean,
      sym_interpolated_string,
      sym_array,
      sym_object,
      sym_arrow_function,
      sym_member_expression,
      sym_subscript_expression,
      sym_call_expression,
  [523] = 12,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_LBRACE,
    ACTIONS(29), 1,
      sym_identifier,
    STATE(22), 1,
      sym_primary_expression,
    STATE(24), 1,
      sym_expression,
    STATE(129), 1,
      sym_formal_parameters,
    ACTIONS(17), 2,
      anon_sym_null,
      anon_sym_none,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(43), 10,
      sym_parenthesized_expression,
      sym_null,
      sym_boolean,
      sym_interpolated_string,
      sym_array,
      sym_object,
      sym_arrow_function,
      sym_member_expression,
      sym_subscript_expression,
      sym_call_expression,
  [572] = 12,
    ACTIONS(41), 1,
      sym_identifier,
    ACTIONS(43), 1,
      anon_sym_LPAREN,
    ACTIONS(51), 1,
      anon_sym_DQUOTE,
    ACTIONS(53), 1,
      anon_sym_LBRACK,
    ACTIONS(55), 1,
      anon_sym_LBRACE,
    STATE(67), 1,
      sym_primary_expression,
    STATE(73), 1,
      sym_expression,
    STATE(127), 1,
      sym_formal_parameters,
    ACTIONS(45), 2,
      anon_sym_null,
      anon_sym_none,
    ACTIONS(47), 2,
      sym_number,
      sym_string,
    ACTIONS(49), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(89), 10,
      sym_parenthesized_expression,
      sym_null,
      sym_boolean,
      sym_interpolated_string,
      sym_array,
      sym_object,
      sym_arrow_function,
      sym_member_expression,
      sym_subscript_expression,
      sym_call_expression,
  [621] = 12,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_LBRACE,
    ACTIONS(29), 1,
      sym_identifier,
    STATE(22), 1,
      sym_primary_expression,
    STATE(75), 1,
      sym_expression,
    STATE(129), 1,
      sym_formal_parameters,
    ACTIONS(17), 2,
      anon_sym_null,
      anon_sym_none,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(43), 10,
      sym_parenthesized_expression,
      sym_null,
      sym_boolean,
      sym_interpolated_string,
      sym_array,
      sym_object,
      sym_arrow_function,
      sym_member_expression,
      sym_subscript_expression,
      sym_call_expression,
  [670] = 12,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_LBRACE,
    ACTIONS(29), 1,
      sym_identifier,
    STATE(22), 1,
      sym_primary_expression,
    STATE(50), 1,
      sym_expression,
    STATE(129), 1,
      sym_formal_parameters,
    ACTIONS(17), 2,
      anon_sym_null,
      anon_sym_none,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(43), 10,
      sym_parenthesized_expression,
      sym_null,
      sym_boolean,
      sym_interpolated_string,
      sym_array,
      sym_object,
      sym_arrow_function,
      sym_member_expression,
      sym_subscript_expression,
      sym_call_expression,
  [719] = 12,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_LBRACE,
    ACTIONS(29), 1,
      sym_identifier,
    STATE(22), 1,
      sym_primary_expression,
    STATE(91), 1,
      sym_expression,
    STATE(129), 1,
      sym_formal_parameters,
    ACTIONS(17), 2,
      anon_sym_null,
      anon_sym_none,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(43), 10,
      sym_parenthesized_expression,
      sym_null,
      sym_boolean,
      sym_interpolated_string,
      sym_array,
      sym_object,
      sym_arrow_function,
      sym_member_expression,
      sym_subscript_expression,
      sym_call_expression,
  [768] = 12,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_LBRACE,
    ACTIONS(29), 1,
      sym_identifier,
    STATE(22), 1,
      sym_primary_expression,
    STATE(25), 1,
      sym_expression,
    STATE(129), 1,
      sym_formal_parameters,
    ACTIONS(17), 2,
      anon_sym_null,
      anon_sym_none,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(43), 10,
      sym_parenthesized_expression,
      sym_null,
      sym_boolean,
      sym_interpolated_string,
      sym_array,
      sym_object,
      sym_arrow_function,
      sym_member_expression,
      sym_subscript_expression,
      sym_call_expression,
  [817] = 12,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_LBRACE,
    ACTIONS(29), 1,
      sym_identifier,
    STATE(22), 1,
      sym_primary_expression,
    STATE(51), 1,
      sym_expression,
    STATE(129), 1,
      sym_formal_parameters,
    ACTIONS(17), 2,
      anon_sym_null,
      anon_sym_none,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(43), 10,
      sym_parenthesized_expression,
      sym_null,
      sym_boolean,
      sym_interpolated_string,
      sym_array,
      sym_object,
      sym_arrow_function,
      sym_member_expression,
      sym_subscript_expression,
      sym_call_expression,
  [866] = 12,
    ACTIONS(41), 1,
      sym_identifier,
    ACTIONS(43), 1,
      anon_sym_LPAREN,
    ACTIONS(51), 1,
      anon_sym_DQUOTE,
    ACTIONS(53), 1,
      anon_sym_LBRACK,
    ACTIONS(55), 1,
      anon_sym_LBRACE,
    STATE(67), 1,
      sym_primary_expression,
    STATE(68), 1,
      sym_expression,
    STATE(127), 1,
      sym_formal_parameters,
    ACTIONS(45), 2,
      anon_sym_null,
      anon_sym_none,
    ACTIONS(47), 2,
      sym_number,
      sym_string,
    ACTIONS(49), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(89), 10,
      sym_parenthesized_expression,
      sym_null,
      sym_boolean,
      sym_interpolated_string,
      sym_array,
      sym_object,
      sym_arrow_function,
      sym_member_expression,
      sym_subscript_expression,
      sym_call_expression,
  [915] = 6,
    ACTIONS(5), 1,
      aux_sym_content_token1,
    ACTIONS(9), 1,
      anon_sym_LBRACE_POUND,
    ACTIONS(57), 1,
      ts_builtin_sym_end,
    STATE(52), 1,
      aux_sym_content_repeat1,
    ACTIONS(7), 3,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_DASH,
      anon_sym_LBRACE_LBRACE_TILDE,
    STATE(21), 5,
      sym__source_element,
      sym_content,
      sym_output_directive,
      sym_comment,
      aux_sym_template_repeat1,
  [940] = 6,
    ACTIONS(59), 1,
      ts_builtin_sym_end,
    ACTIONS(61), 1,
      aux_sym_content_token1,
    ACTIONS(67), 1,
      anon_sym_LBRACE_POUND,
    STATE(52), 1,
      aux_sym_content_repeat1,
    ACTIONS(64), 3,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_DASH,
      anon_sym_LBRACE_LBRACE_TILDE,
    STATE(21), 5,
      sym__source_element,
      sym_content,
      sym_output_directive,
      sym_comment,
      aux_sym_template_repeat1,
  [965] = 5,
    ACTIONS(72), 1,
      anon_sym_LPAREN,
    ACTIONS(74), 1,
      anon_sym_LBRACK,
    ACTIONS(76), 1,
      anon_sym_DOT,
    STATE(27), 1,
      sym_arguments,
    ACTIONS(70), 6,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_TILDE_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [986] = 2,
    ACTIONS(80), 1,
      anon_sym_EQ_GT,
    ACTIONS(78), 9,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_TILDE_RBRACE_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DOT,
  [1001] = 5,
    ACTIONS(72), 1,
      anon_sym_LPAREN,
    ACTIONS(74), 1,
      anon_sym_LBRACK,
    ACTIONS(76), 1,
      anon_sym_DOT,
    STATE(46), 1,
      sym_arguments,
    ACTIONS(82), 6,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_TILDE_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1022] = 5,
    ACTIONS(72), 1,
      anon_sym_LPAREN,
    ACTIONS(74), 1,
      anon_sym_LBRACK,
    ACTIONS(76), 1,
      anon_sym_DOT,
    STATE(46), 1,
      sym_arguments,
    ACTIONS(84), 6,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_TILDE_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1043] = 1,
    ACTIONS(86), 9,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_TILDE_RBRACE_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DOT,
  [1055] = 1,
    ACTIONS(88), 9,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_TILDE_RBRACE_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DOT,
  [1067] = 1,
    ACTIONS(90), 9,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_TILDE_RBRACE_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DOT,
  [1079] = 1,
    ACTIONS(92), 9,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_TILDE_RBRACE_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DOT,
  [1091] = 1,
    ACTIONS(94), 9,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_TILDE_RBRACE_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DOT,
  [1103] = 1,
    ACTIONS(96), 9,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_TILDE_RBRACE_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DOT,
  [1115] = 1,
    ACTIONS(98), 9,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_TILDE_RBRACE_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DOT,
  [1127] = 1,
    ACTIONS(100), 9,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_TILDE_RBRACE_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DOT,
  [1139] = 1,
    ACTIONS(102), 9,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_TILDE_RBRACE_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DOT,
  [1151] = 1,
    ACTIONS(104), 9,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_TILDE_RBRACE_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DOT,
  [1163] = 1,
    ACTIONS(106), 9,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_TILDE_RBRACE_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DOT,
  [1175] = 1,
    ACTIONS(108), 9,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_TILDE_RBRACE_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DOT,
  [1187] = 1,
    ACTIONS(110), 9,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_TILDE_RBRACE_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DOT,
  [1199] = 1,
    ACTIONS(112), 9,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_TILDE_RBRACE_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DOT,
  [1211] = 1,
    ACTIONS(114), 9,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_TILDE_RBRACE_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DOT,
  [1223] = 1,
    ACTIONS(116), 9,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_TILDE_RBRACE_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DOT,
  [1235] = 1,
    ACTIONS(118), 9,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_TILDE_RBRACE_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DOT,
  [1247] = 1,
    ACTIONS(78), 9,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_TILDE_RBRACE_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DOT,
  [1259] = 1,
    ACTIONS(120), 9,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_TILDE_RBRACE_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DOT,
  [1271] = 1,
    ACTIONS(122), 9,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_TILDE_RBRACE_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DOT,
  [1283] = 1,
    ACTIONS(88), 9,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_TILDE_RBRACE_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DOT,
  [1295] = 6,
    ACTIONS(124), 1,
      sym_identifier,
    ACTIONS(126), 1,
      anon_sym_RBRACE,
    ACTIONS(128), 1,
      anon_sym_LPAREN,
    STATE(117), 1,
      sym_pair,
    ACTIONS(130), 2,
      sym_number,
      sym_string,
    STATE(128), 2,
      sym__property_name,
      sym_computed_property_name,
  [1316] = 6,
    ACTIONS(128), 1,
      anon_sym_LPAREN,
    ACTIONS(132), 1,
      sym_identifier,
    ACTIONS(134), 1,
      anon_sym_RBRACE,
    STATE(120), 1,
      sym_pair,
    ACTIONS(130), 2,
      sym_number,
      sym_string,
    STATE(128), 2,
      sym__property_name,
      sym_computed_property_name,
  [1337] = 7,
    ACTIONS(72), 1,
      anon_sym_LPAREN,
    ACTIONS(74), 1,
      anon_sym_LBRACK,
    ACTIONS(76), 1,
      anon_sym_DOT,
    ACTIONS(136), 1,
      anon_sym_COMMA,
    ACTIONS(138), 1,
      anon_sym_RBRACK,
    STATE(46), 1,
      sym_arguments,
    STATE(116), 1,
      aux_sym_array_repeat1,
  [1359] = 5,
    ACTIONS(72), 1,
      anon_sym_LPAREN,
    ACTIONS(74), 1,
      anon_sym_LBRACK,
    ACTIONS(76), 1,
      anon_sym_DOT,
    STATE(46), 1,
      sym_arguments,
    ACTIONS(140), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1377] = 5,
    ACTIONS(72), 1,
      anon_sym_LPAREN,
    ACTIONS(74), 1,
      anon_sym_LBRACK,
    ACTIONS(76), 1,
      anon_sym_DOT,
    STATE(46), 1,
      sym_arguments,
    ACTIONS(142), 3,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_TILDE_RBRACE_RBRACE,
  [1395] = 4,
    ACTIONS(144), 1,
      ts_builtin_sym_end,
    ACTIONS(146), 1,
      aux_sym_content_token1,
    STATE(60), 1,
      aux_sym_content_repeat1,
    ACTIONS(148), 4,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_DASH,
      anon_sym_LBRACE_LBRACE_TILDE,
      anon_sym_LBRACE_POUND,
  [1411] = 5,
    ACTIONS(150), 1,
      anon_sym_DQUOTE,
    ACTIONS(154), 1,
      aux_sym_interpolated_string_token1,
    ACTIONS(156), 1,
      anon_sym_POUND_LBRACE,
    STATE(62), 1,
      aux_sym_interpolated_string_repeat1,
    ACTIONS(152), 3,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_POUND,
      anon_sym_BSLASH_BSLASH,
  [1429] = 7,
    ACTIONS(72), 1,
      anon_sym_LPAREN,
    ACTIONS(74), 1,
      anon_sym_LBRACK,
    ACTIONS(76), 1,
      anon_sym_DOT,
    ACTIONS(136), 1,
      anon_sym_COMMA,
    ACTIONS(158), 1,
      anon_sym_RPAREN,
    STATE(46), 1,
      sym_arguments,
    STATE(110), 1,
      aux_sym_array_repeat1,
  [1451] = 5,
    ACTIONS(156), 1,
      anon_sym_POUND_LBRACE,
    ACTIONS(160), 1,
      anon_sym_DQUOTE,
    ACTIONS(164), 1,
      aux_sym_interpolated_string_token1,
    STATE(58), 1,
      aux_sym_interpolated_string_repeat1,
    ACTIONS(162), 3,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_POUND,
      anon_sym_BSLASH_BSLASH,
  [1469] = 7,
    ACTIONS(72), 1,
      anon_sym_LPAREN,
    ACTIONS(74), 1,
      anon_sym_LBRACK,
    ACTIONS(76), 1,
      anon_sym_DOT,
    ACTIONS(136), 1,
      anon_sym_COMMA,
    ACTIONS(166), 1,
      anon_sym_RBRACK,
    STATE(46), 1,
      sym_arguments,
    STATE(114), 1,
      aux_sym_array_repeat1,
  [1491] = 5,
    ACTIONS(168), 1,
      anon_sym_DQUOTE,
    ACTIONS(173), 1,
      aux_sym_interpolated_string_token1,
    ACTIONS(176), 1,
      anon_sym_POUND_LBRACE,
    STATE(57), 1,
      aux_sym_interpolated_string_repeat1,
    ACTIONS(170), 3,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_POUND,
      anon_sym_BSLASH_BSLASH,
  [1509] = 5,
    ACTIONS(156), 1,
      anon_sym_POUND_LBRACE,
    ACTIONS(179), 1,
      anon_sym_DQUOTE,
    ACTIONS(183), 1,
      aux_sym_interpolated_string_token1,
    STATE(57), 1,
      aux_sym_interpolated_string_repeat1,
    ACTIONS(181), 3,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_POUND,
      anon_sym_BSLASH_BSLASH,
  [1527] = 7,
    ACTIONS(72), 1,
      anon_sym_LPAREN,
    ACTIONS(74), 1,
      anon_sym_LBRACK,
    ACTIONS(76), 1,
      anon_sym_DOT,
    ACTIONS(136), 1,
      anon_sym_COMMA,
    ACTIONS(185), 1,
      anon_sym_RPAREN,
    STATE(46), 1,
      sym_arguments,
    STATE(106), 1,
      aux_sym_array_repeat1,
  [1549] = 4,
    ACTIONS(187), 1,
      ts_builtin_sym_end,
    ACTIONS(189), 1,
      aux_sym_content_token1,
    STATE(60), 1,
      aux_sym_content_repeat1,
    ACTIONS(192), 4,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_DASH,
      anon_sym_LBRACE_LBRACE_TILDE,
      anon_sym_LBRACE_POUND,
  [1565] = 5,
    ACTIONS(128), 1,
      anon_sym_LPAREN,
    ACTIONS(194), 1,
      sym_identifier,
    STATE(121), 1,
      sym_pair,
    ACTIONS(130), 2,
      sym_number,
      sym_string,
    STATE(128), 2,
      sym__property_name,
      sym_computed_property_name,
  [1583] = 5,
    ACTIONS(156), 1,
      anon_sym_POUND_LBRACE,
    ACTIONS(183), 1,
      aux_sym_interpolated_string_token1,
    ACTIONS(196), 1,
      anon_sym_DQUOTE,
    STATE(57), 1,
      aux_sym_interpolated_string_repeat1,
    ACTIONS(181), 3,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_POUND,
      anon_sym_BSLASH_BSLASH,
  [1601] = 3,
    ACTIONS(80), 1,
      anon_sym_EQ_GT,
    ACTIONS(198), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
    ACTIONS(78), 3,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_DOT,
  [1614] = 4,
    ACTIONS(80), 1,
      anon_sym_EQ_GT,
    ACTIONS(198), 1,
      anon_sym_COMMA,
    ACTIONS(200), 1,
      anon_sym_RPAREN,
    ACTIONS(78), 3,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_DOT,
  [1629] = 2,
    ACTIONS(203), 1,
      ts_builtin_sym_end,
    ACTIONS(205), 5,
      aux_sym_content_token1,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_DASH,
      anon_sym_LBRACE_LBRACE_TILDE,
      anon_sym_LBRACE_POUND,
  [1640] = 2,
    ACTIONS(207), 1,
      anon_sym_EQ_GT,
    ACTIONS(78), 5,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_DOT,
  [1651] = 5,
    ACTIONS(209), 1,
      anon_sym_LPAREN,
    ACTIONS(211), 1,
      anon_sym_LBRACK,
    ACTIONS(213), 1,
      anon_sym_DOT,
    STATE(99), 1,
      sym_arguments,
    ACTIONS(70), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1668] = 5,
    ACTIONS(209), 1,
      anon_sym_LPAREN,
    ACTIONS(211), 1,
      anon_sym_LBRACK,
    ACTIONS(213), 1,
      anon_sym_DOT,
    STATE(98), 1,
      sym_arguments,
    ACTIONS(215), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1685] = 5,
    ACTIONS(209), 1,
      anon_sym_LPAREN,
    ACTIONS(211), 1,
      anon_sym_LBRACK,
    ACTIONS(213), 1,
      anon_sym_DOT,
    STATE(98), 1,
      sym_arguments,
    ACTIONS(82), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1702] = 5,
    ACTIONS(209), 1,
      anon_sym_LPAREN,
    ACTIONS(211), 1,
      anon_sym_LBRACK,
    ACTIONS(213), 1,
      anon_sym_DOT,
    STATE(98), 1,
      sym_arguments,
    ACTIONS(84), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1719] = 2,
    ACTIONS(217), 1,
      ts_builtin_sym_end,
    ACTIONS(219), 5,
      aux_sym_content_token1,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_DASH,
      anon_sym_LBRACE_LBRACE_TILDE,
      anon_sym_LBRACE_POUND,
  [1730] = 2,
    ACTIONS(223), 1,
      aux_sym_interpolated_string_token1,
    ACTIONS(221), 5,
      anon_sym_DQUOTE,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_POUND,
      anon_sym_BSLASH_BSLASH,
      anon_sym_POUND_LBRACE,
  [1741] = 5,
    ACTIONS(209), 1,
      anon_sym_LPAREN,
    ACTIONS(211), 1,
      anon_sym_LBRACK,
    ACTIONS(213), 1,
      anon_sym_DOT,
    ACTIONS(225), 1,
      anon_sym_RBRACE,
    STATE(98), 1,
      sym_arguments,
  [1757] = 1,
    ACTIONS(112), 5,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_DOT,
  [1765] = 5,
    ACTIONS(72), 1,
      anon_sym_LPAREN,
    ACTIONS(74), 1,
      anon_sym_LBRACK,
    ACTIONS(76), 1,
      anon_sym_DOT,
    ACTIONS(227), 1,
      anon_sym_RBRACK,
    STATE(46), 1,
      sym_arguments,
  [1781] = 5,
    ACTIONS(72), 1,
      anon_sym_LPAREN,
    ACTIONS(74), 1,
      anon_sym_LBRACK,
    ACTIONS(76), 1,
      anon_sym_DOT,
    ACTIONS(229), 1,
      anon_sym_RPAREN,
    STATE(46), 1,
      sym_arguments,
  [1797] = 3,
    ACTIONS(198), 1,
      anon_sym_COMMA,
    ACTIONS(200), 1,
      anon_sym_RPAREN,
    ACTIONS(78), 3,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_DOT,
  [1809] = 5,
    ACTIONS(72), 1,
      anon_sym_LPAREN,
    ACTIONS(74), 1,
      anon_sym_LBRACK,
    ACTIONS(76), 1,
      anon_sym_DOT,
    ACTIONS(231), 1,
      anon_sym_RPAREN,
    STATE(46), 1,
      sym_arguments,
  [1825] = 1,
    ACTIONS(106), 5,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_DOT,
  [1833] = 1,
    ACTIONS(102), 5,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_DOT,
  [1841] = 1,
    ACTIONS(96), 5,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_DOT,
  [1849] = 1,
    ACTIONS(90), 5,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_DOT,
  [1857] = 1,
    ACTIONS(92), 5,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_DOT,
  [1865] = 1,
    ACTIONS(94), 5,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_DOT,
  [1873] = 5,
    ACTIONS(72), 1,
      anon_sym_LPAREN,
    ACTIONS(74), 1,
      anon_sym_LBRACK,
    ACTIONS(76), 1,
      anon_sym_DOT,
    ACTIONS(233), 1,
      anon_sym_RBRACK,
    STATE(46), 1,
      sym_arguments,
  [1889] = 1,
    ACTIONS(86), 5,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_DOT,
  [1897] = 1,
    ACTIONS(98), 5,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_DOT,
  [1905] = 1,
    ACTIONS(100), 5,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_DOT,
  [1913] = 1,
    ACTIONS(78), 5,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_DOT,
  [1921] = 1,
    ACTIONS(120), 5,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_DOT,
  [1929] = 5,
    ACTIONS(72), 1,
      anon_sym_LPAREN,
    ACTIONS(74), 1,
      anon_sym_LBRACK,
    ACTIONS(76), 1,
      anon_sym_DOT,
    ACTIONS(235), 1,
      anon_sym_RPAREN,
    STATE(46), 1,
      sym_arguments,
  [1945] = 1,
    ACTIONS(104), 5,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_DOT,
  [1953] = 2,
    ACTIONS(198), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
    ACTIONS(78), 3,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_DOT,
  [1963] = 1,
    ACTIONS(108), 5,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_DOT,
  [1971] = 1,
    ACTIONS(110), 5,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_DOT,
  [1979] = 1,
    ACTIONS(114), 5,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_DOT,
  [1987] = 1,
    ACTIONS(118), 5,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_DOT,
  [1995] = 1,
    ACTIONS(88), 5,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_DOT,
  [2003] = 1,
    ACTIONS(88), 5,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_DOT,
  [2011] = 1,
    ACTIONS(116), 5,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_DOT,
  [2019] = 1,
    ACTIONS(122), 5,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_DOT,
  [2027] = 4,
    ACTIONS(72), 1,
      anon_sym_LPAREN,
    ACTIONS(74), 1,
      anon_sym_LBRACK,
    ACTIONS(76), 1,
      anon_sym_DOT,
    STATE(46), 1,
      sym_arguments,
  [2040] = 4,
    ACTIONS(237), 1,
      anon_sym_RBRACE,
    ACTIONS(239), 1,
      anon_sym_COMMA,
    ACTIONS(241), 1,
      anon_sym_COLON,
    STATE(112), 1,
      aux_sym_object_repeat1,
  [2053] = 3,
    ACTIONS(243), 1,
      anon_sym_COMMA,
    STATE(104), 1,
      aux_sym_array_repeat1,
    ACTIONS(140), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [2064] = 4,
    ACTIONS(239), 1,
      anon_sym_COMMA,
    ACTIONS(241), 1,
      anon_sym_COLON,
    ACTIONS(246), 1,
      anon_sym_RBRACE,
    STATE(108), 1,
      aux_sym_object_repeat1,
  [2077] = 3,
    ACTIONS(136), 1,
      anon_sym_COMMA,
    ACTIONS(248), 1,
      anon_sym_RPAREN,
    STATE(104), 1,
      aux_sym_array_repeat1,
  [2087] = 3,
    ACTIONS(250), 1,
      anon_sym_RPAREN,
    ACTIONS(252), 1,
      anon_sym_COMMA,
    STATE(118), 1,
      aux_sym_formal_parameters_repeat1,
  [2097] = 3,
    ACTIONS(239), 1,
      anon_sym_COMMA,
    ACTIONS(254), 1,
      anon_sym_RBRACE,
    STATE(113), 1,
      aux_sym_object_repeat1,
  [2107] = 3,
    ACTIONS(239), 1,
      anon_sym_COMMA,
    ACTIONS(256), 1,
      anon_sym_RBRACE,
    STATE(113), 1,
      aux_sym_object_repeat1,
  [2117] = 3,
    ACTIONS(136), 1,
      anon_sym_COMMA,
    ACTIONS(258), 1,
      anon_sym_RPAREN,
    STATE(104), 1,
      aux_sym_array_repeat1,
  [2127] = 3,
    ACTIONS(239), 1,
      anon_sym_COMMA,
    ACTIONS(260), 1,
      anon_sym_RBRACE,
    STATE(113), 1,
      aux_sym_object_repeat1,
  [2137] = 3,
    ACTIONS(239), 1,
      anon_sym_COMMA,
    ACTIONS(262), 1,
      anon_sym_RBRACE,
    STATE(113), 1,
      aux_sym_object_repeat1,
  [2147] = 3,
    ACTIONS(264), 1,
      anon_sym_RBRACE,
    ACTIONS(266), 1,
      anon_sym_COMMA,
    STATE(113), 1,
      aux_sym_object_repeat1,
  [2157] = 3,
    ACTIONS(136), 1,
      anon_sym_COMMA,
    ACTIONS(269), 1,
      anon_sym_RBRACK,
    STATE(104), 1,
      aux_sym_array_repeat1,
  [2167] = 2,
    ACTIONS(241), 1,
      anon_sym_COLON,
    ACTIONS(271), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [2175] = 3,
    ACTIONS(136), 1,
      anon_sym_COMMA,
    ACTIONS(273), 1,
      anon_sym_RBRACK,
    STATE(104), 1,
      aux_sym_array_repeat1,
  [2185] = 3,
    ACTIONS(239), 1,
      anon_sym_COMMA,
    ACTIONS(275), 1,
      anon_sym_RBRACE,
    STATE(109), 1,
      aux_sym_object_repeat1,
  [2195] = 3,
    ACTIONS(252), 1,
      anon_sym_COMMA,
    ACTIONS(277), 1,
      anon_sym_RPAREN,
    STATE(119), 1,
      aux_sym_formal_parameters_repeat1,
  [2205] = 3,
    ACTIONS(279), 1,
      anon_sym_RPAREN,
    ACTIONS(281), 1,
      anon_sym_COMMA,
    STATE(119), 1,
      aux_sym_formal_parameters_repeat1,
  [2215] = 3,
    ACTIONS(239), 1,
      anon_sym_COMMA,
    ACTIONS(284), 1,
      anon_sym_RBRACE,
    STATE(111), 1,
      aux_sym_object_repeat1,
  [2225] = 1,
    ACTIONS(264), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [2230] = 1,
    ACTIONS(279), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [2235] = 1,
    ACTIONS(286), 1,
      aux_sym_comment_token1,
  [2239] = 1,
    ACTIONS(288), 1,
      sym_identifier,
  [2243] = 1,
    ACTIONS(290), 1,
      anon_sym_COLON,
  [2247] = 1,
    ACTIONS(292), 1,
      sym_identifier,
  [2251] = 1,
    ACTIONS(294), 1,
      anon_sym_EQ_GT,
  [2255] = 1,
    ACTIONS(296), 1,
      anon_sym_COLON,
  [2259] = 1,
    ACTIONS(298), 1,
      anon_sym_EQ_GT,
  [2263] = 1,
    ACTIONS(300), 1,
      anon_sym_EQ_GT,
  [2267] = 1,
    ACTIONS(302), 1,
      anon_sym_EQ_GT,
  [2271] = 1,
    ACTIONS(304), 1,
      anon_sym_EQ_GT,
  [2275] = 1,
    ACTIONS(306), 1,
      anon_sym_RBRACE,
  [2279] = 1,
    ACTIONS(308), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 57,
  [SMALL_STATE(4)] = 114,
  [SMALL_STATE(5)] = 166,
  [SMALL_STATE(6)] = 218,
  [SMALL_STATE(7)] = 272,
  [SMALL_STATE(8)] = 324,
  [SMALL_STATE(9)] = 376,
  [SMALL_STATE(10)] = 425,
  [SMALL_STATE(11)] = 474,
  [SMALL_STATE(12)] = 523,
  [SMALL_STATE(13)] = 572,
  [SMALL_STATE(14)] = 621,
  [SMALL_STATE(15)] = 670,
  [SMALL_STATE(16)] = 719,
  [SMALL_STATE(17)] = 768,
  [SMALL_STATE(18)] = 817,
  [SMALL_STATE(19)] = 866,
  [SMALL_STATE(20)] = 915,
  [SMALL_STATE(21)] = 940,
  [SMALL_STATE(22)] = 965,
  [SMALL_STATE(23)] = 986,
  [SMALL_STATE(24)] = 1001,
  [SMALL_STATE(25)] = 1022,
  [SMALL_STATE(26)] = 1043,
  [SMALL_STATE(27)] = 1055,
  [SMALL_STATE(28)] = 1067,
  [SMALL_STATE(29)] = 1079,
  [SMALL_STATE(30)] = 1091,
  [SMALL_STATE(31)] = 1103,
  [SMALL_STATE(32)] = 1115,
  [SMALL_STATE(33)] = 1127,
  [SMALL_STATE(34)] = 1139,
  [SMALL_STATE(35)] = 1151,
  [SMALL_STATE(36)] = 1163,
  [SMALL_STATE(37)] = 1175,
  [SMALL_STATE(38)] = 1187,
  [SMALL_STATE(39)] = 1199,
  [SMALL_STATE(40)] = 1211,
  [SMALL_STATE(41)] = 1223,
  [SMALL_STATE(42)] = 1235,
  [SMALL_STATE(43)] = 1247,
  [SMALL_STATE(44)] = 1259,
  [SMALL_STATE(45)] = 1271,
  [SMALL_STATE(46)] = 1283,
  [SMALL_STATE(47)] = 1295,
  [SMALL_STATE(48)] = 1316,
  [SMALL_STATE(49)] = 1337,
  [SMALL_STATE(50)] = 1359,
  [SMALL_STATE(51)] = 1377,
  [SMALL_STATE(52)] = 1395,
  [SMALL_STATE(53)] = 1411,
  [SMALL_STATE(54)] = 1429,
  [SMALL_STATE(55)] = 1451,
  [SMALL_STATE(56)] = 1469,
  [SMALL_STATE(57)] = 1491,
  [SMALL_STATE(58)] = 1509,
  [SMALL_STATE(59)] = 1527,
  [SMALL_STATE(60)] = 1549,
  [SMALL_STATE(61)] = 1565,
  [SMALL_STATE(62)] = 1583,
  [SMALL_STATE(63)] = 1601,
  [SMALL_STATE(64)] = 1614,
  [SMALL_STATE(65)] = 1629,
  [SMALL_STATE(66)] = 1640,
  [SMALL_STATE(67)] = 1651,
  [SMALL_STATE(68)] = 1668,
  [SMALL_STATE(69)] = 1685,
  [SMALL_STATE(70)] = 1702,
  [SMALL_STATE(71)] = 1719,
  [SMALL_STATE(72)] = 1730,
  [SMALL_STATE(73)] = 1741,
  [SMALL_STATE(74)] = 1757,
  [SMALL_STATE(75)] = 1765,
  [SMALL_STATE(76)] = 1781,
  [SMALL_STATE(77)] = 1797,
  [SMALL_STATE(78)] = 1809,
  [SMALL_STATE(79)] = 1825,
  [SMALL_STATE(80)] = 1833,
  [SMALL_STATE(81)] = 1841,
  [SMALL_STATE(82)] = 1849,
  [SMALL_STATE(83)] = 1857,
  [SMALL_STATE(84)] = 1865,
  [SMALL_STATE(85)] = 1873,
  [SMALL_STATE(86)] = 1889,
  [SMALL_STATE(87)] = 1897,
  [SMALL_STATE(88)] = 1905,
  [SMALL_STATE(89)] = 1913,
  [SMALL_STATE(90)] = 1921,
  [SMALL_STATE(91)] = 1929,
  [SMALL_STATE(92)] = 1945,
  [SMALL_STATE(93)] = 1953,
  [SMALL_STATE(94)] = 1963,
  [SMALL_STATE(95)] = 1971,
  [SMALL_STATE(96)] = 1979,
  [SMALL_STATE(97)] = 1987,
  [SMALL_STATE(98)] = 1995,
  [SMALL_STATE(99)] = 2003,
  [SMALL_STATE(100)] = 2011,
  [SMALL_STATE(101)] = 2019,
  [SMALL_STATE(102)] = 2027,
  [SMALL_STATE(103)] = 2040,
  [SMALL_STATE(104)] = 2053,
  [SMALL_STATE(105)] = 2064,
  [SMALL_STATE(106)] = 2077,
  [SMALL_STATE(107)] = 2087,
  [SMALL_STATE(108)] = 2097,
  [SMALL_STATE(109)] = 2107,
  [SMALL_STATE(110)] = 2117,
  [SMALL_STATE(111)] = 2127,
  [SMALL_STATE(112)] = 2137,
  [SMALL_STATE(113)] = 2147,
  [SMALL_STATE(114)] = 2157,
  [SMALL_STATE(115)] = 2167,
  [SMALL_STATE(116)] = 2175,
  [SMALL_STATE(117)] = 2185,
  [SMALL_STATE(118)] = 2195,
  [SMALL_STATE(119)] = 2205,
  [SMALL_STATE(120)] = 2215,
  [SMALL_STATE(121)] = 2225,
  [SMALL_STATE(122)] = 2230,
  [SMALL_STATE(123)] = 2235,
  [SMALL_STATE(124)] = 2239,
  [SMALL_STATE(125)] = 2243,
  [SMALL_STATE(126)] = 2247,
  [SMALL_STATE(127)] = 2251,
  [SMALL_STATE(128)] = 2255,
  [SMALL_STATE(129)] = 2259,
  [SMALL_STATE(130)] = 2263,
  [SMALL_STATE(131)] = 2267,
  [SMALL_STATE(132)] = 2271,
  [SMALL_STATE(133)] = 2275,
  [SMALL_STATE(134)] = 2279,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(123),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(130),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(88),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(90),
  [51] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template, 1),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2),
  [61] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_template_repeat1, 2), SHIFT_REPEAT(52),
  [64] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_template_repeat1, 2), SHIFT_REPEAT(18),
  [67] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_template_repeat1, 2), SHIFT_REPEAT(123),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primary_expression, 1),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arrow_function, 3, .production_id = 3),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arrow_function, 3, .production_id = 6),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_member_expression, 3, .production_id = 5),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_expression, 2, .production_id = 2),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 4),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 4, .production_id = 4),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 4),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 3),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 2),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_null, 1),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subscript_expression, 4, .production_id = 8),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 3),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 4),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 3, .production_id = 4),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interpolated_string, 2),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 3),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 2),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interpolated_string, 3),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 2),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parenthesized_expression, 3),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(128),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_content, 1),
  [146] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_content, 1),
  [150] = {.entry = {.count = 1, .reusable = false}}, SHIFT(95),
  [152] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [156] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [160] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [162] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [168] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_interpolated_string_repeat1, 2),
  [170] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_interpolated_string_repeat1, 2), SHIFT_REPEAT(57),
  [173] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_interpolated_string_repeat1, 2), SHIFT_REPEAT(57),
  [176] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_interpolated_string_repeat1, 2), SHIFT_REPEAT(13),
  [179] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [181] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_content_repeat1, 2),
  [189] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_content_repeat1, 2), SHIFT_REPEAT(60),
  [192] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_content_repeat1, 2),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [196] = {.entry = {.count = 1, .reusable = false}}, SHIFT(100),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern, 1, .dynamic_precedence = -1),
  [200] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_primary_expression, 1), REDUCE(sym_pattern, 1, .dynamic_precedence = -1),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_output_directive, 3),
  [205] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_output_directive, 3),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pair, 3, .production_id = 7),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3),
  [219] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 3),
  [221] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_interpolated_string_repeat1, 3),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_interpolated_string_repeat1, 3),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [241] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__property_name, 1, .production_id = 1),
  [243] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(15),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(132),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [264] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_object_repeat1, 2),
  [266] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_object_repeat1, 2), SHIFT_REPEAT(61),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [271] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_object_repeat1, 2, .production_id = 4),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(131),
  [279] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_formal_parameters_repeat1, 2),
  [281] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_formal_parameters_repeat1, 2), SHIFT_REPEAT(6),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(133),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [290] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_computed_property_name, 3),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [300] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_formal_parameters, 2),
  [302] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_formal_parameters, 4),
  [304] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_formal_parameters, 3),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [308] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_twig(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
